In [1]:
import pandas as pd 
import requests
from jsonschema import validate
import json
import fastparquet

In [54]:
pd.set_option('display.width', None)

In [31]:
countriesDf = pd.DataFrame(pd.read_parquet('../dataRawBeforeBlob/countries/euCountriesRaw.parquet'))
countriesDf

,Code,Title,ParentDimension,Dimension,ParentCode,ParentTitle
0,AUT,Austria,REGION,COUNTRY,EUR,Europe
1,BEL,Belgium,REGION,COUNTRY,EUR,Europe
2,BGR,Bulgaria,REGION,COUNTRY,EUR,Europe
3,CYP,Cyprus,REGION,COUNTRY,EUR,Europe
4,CZE,Czechia,REGION,COUNTRY,EUR,Europe
5,DEU,Germany,REGION,COUNTRY,EUR,Europe
6,DNK,Denmark,REGION,COUNTRY,EUR,Europe
7,ESP,Spain,REGION,COUNTRY,EUR,Europe
8,EST,Estonia,REGION,COUNTRY,EUR,Europe
9,FIN,Finland,REGION,COUNTRY,EUR,Europe
10,FRA,France,REGION,COUNTRY,EUR,Europe
11,GRC,Greece,REGION,COUNTRY,EUR,Europe
12,HRV,Croatia,REGION,COUNTRY,EUR,Europe
13,HUN,Hungary,REGION,COUNTRY,EUR,Europe
14,IRL,Ireland,REGION,COUNTRY,EUR,Europe
15,ITA,Italy,REGION,COUNTRY,EUR,Europe
16,LTU,Lithuania,REGION,COUNTRY,EUR,Europe
17,LUX,Luxembourg,REGION,COUNTRY,EUR,Europe
18,LVA,Latvia,REGION,COUNTRY,EUR,Europe
19,MLT,Malta,REGION,COUNTRY,EUR,Europe
20,NLD,Netherlands (Kingdom of the),REGION,COUNTRY,EUR,Europe
21,POL,Poland,REGION,COUNTRY,EUR,Europe
22,PRT,Portugal,REGION,COUNTRY,EUR,Europe
23,ROU,Romania,REGION,COUNTRY,EUR,Europe
24,SVK,Slovakia,REGION,COUNTRY,EUR,Europe
25,SVN,Slovenia,REGION,COUNTRY,EUR,Europe
26,SWE,Sweden,REGION,COUNTRY,EUR,Europe

In [9]:
tobaccoIndicatorsDf = pd.DataFrame(pd.read_parquet('../dataRawBeforeBlob/indicators/tobaccoIndicators.parquet',engine='fastparquet'))
tobaccoIndicatorsDf

,IndicatorCode,IndicatorName,Language,Category
0,R_afford_gdp,Affordability - percentage of GDP per capita r...,EN,Tobacco control: Raise taxes on tobacco
1,TOB_R_PRICE,Retail price for tobacco and nicotine products,EN,Tobacco control: Raise taxes on tobacco
2,E1_nat_tv_radio,Ban on advertising: National TV and radio,EN,Tobacco control: Enforce bans on tobacco adver...
3,E6a_pt_of_sale,Ban on advertising at point of sale,EN,Tobacco control: Enforce bans on tobacco adver...
4,E5_billboards,Ban on advertising: Billboards and outdoor adv...,EN,Tobacco control: Enforce bans on tobacco adver...
5,E7_internet,Ban on advertising: Internet,EN,Tobacco control: Enforce bans on tobacco adver...
6,P6_restaurants,National smoking ban in RESTAURANTS,EN,Tobacco control: Protect from tobacco smoke
7,P8_pub_transp,National smoking ban in PUBLIC TRANSPORT,EN,Tobacco control: Protect from tobacco smoke
8,P5_indoor_off,National smoking ban in INDOOR OFFICES,EN,Tobacco control: Protect from tobacco smoke

In [2]:
baseURL= 'https://ghoapi.azureedge.net/api/'

In [28]:
def getData(baseurl,indicatorCode:str):
    indicatorCode = indicatorCode.strip()
    response = requests.get(baseurl+f"{indicatorCode}")
    return response.json()

In [79]:
def saveToParquet(df: pd.DataFrame,filename):
    df.to_parquet(f'../dataRawBeforeBlob/tobaccoData/{filename}.parquet',engine='fastparquet')

First indicator

In [17]:
firstIndicator = tobaccoIndicatorsDf.iloc[0]
firstIndicator

IndicatorCode                                         R_afford_gdp
IndicatorName    Affordability - percentage of GDP per capita r...
Language                                                        EN
Category                   Tobacco control: Raise taxes on tobacco
Name: 0, dtype: object

In [39]:
firstIndicatorData = getData(baseURL,firstIndicator['IndicatorCode'])
firstIndicatorData = firstIndicatorData['value']
firstIndicatorDataDataFrame = pd.DataFrame(firstIndicatorData)
firstIndicatorDataDataFrame =  firstIndicatorDataDataFrame.loc[firstIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
firstIndicatorDataDataFrame = firstIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Value']]
firstIndicatorDataDataFrame

            Id IndicatorCode SpatialDim  TimeDim Value
4      1898831  R_afford_gdp        GRC     2014  2.47
7      2785705  R_afford_gdp        BEL     2014  1.61
40      298771  R_afford_gdp        NLD     2014  1.58
45     4405899  R_afford_gdp        LUX     2018  0.53
66    10142682  R_afford_gdp        DEU     2018  1.58
...        ...           ...        ...      ...   ...
1132   4747273  R_afford_gdp        IRL     2016  1.91
1134   8925205  R_afford_gdp        GRC     2020  2.98
1136   8324747  R_afford_gdp        CZE     2020  2.02
1141   9083506  R_afford_gdp        DEU     2020  1.71
1157  10186453  R_afford_gdp        DEU     2012  1.54

[162 rows x 5 columns]

In [42]:
saveToParquet(firstIndicatorDataDataFrame,'affordability')

In [43]:
secondIndicator = tobaccoIndicatorsDf.iloc[1]
secondIndicator

IndicatorCode                                       TOB_R_PRICE
IndicatorName    Retail price for tobacco and nicotine products
Language                                                     EN
Category                Tobacco control: Raise taxes on tobacco
Name: 1, dtype: object

In [46]:
secondIndicatorData = getData(baseURL,secondIndicator['IndicatorCode'])
secondIndicatorData = secondIndicatorData['value']
secondIndicatorData

[{'Id': 8859,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KWT',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2016,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_CURRENCY',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'KWD',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-12-15T15:32:24+01:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 14624,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SSD',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2022,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_ELIQUID_CLOSED_DISPOSABLE_CHEAPEST',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_CURRENCY',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': None,
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-01-12T12:38:18+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 15445,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'VNM',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2020,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_CURRENCY',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'VND',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-12-15T15:32:18+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 15562,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'IRQ',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2022,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_CURRENCY',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'IQD',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-12-15T15:32:18+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 20332,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'COD',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2022,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_TOBACCO_SMOKELESS_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_PPP',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': None,
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-01-11T16:57:08+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 27954,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SOM',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2022,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_ELIQUID_CLOSED_RECHARGABLE_CHEAPEST',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_CURRENCY',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': None,
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-01-19T14:35:08+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 28090,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MRT',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2016,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_USD',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '0.86',
  'NumericValue': 0.86,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-12-15T15:32:52+01:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 28371,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AZE',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2018,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_USD',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '0.71',
  'NumericValue': 0.71,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-12-15T15:32:30+01:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 34234,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AGO',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2022,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_ELIQUID_OPEN_CHEAPEST',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_CURRENCY',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': None,
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-01-19T14:46:23+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 39565,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PHL',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2010,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_PPP',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '0.78',
  'NumericValue': 0.78,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-12-15T15:31:52+01:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 40154,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KOR',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2010,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_CURRENCY',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'KRW',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-12-15T15:31:55+01:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 40356,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ROU',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2022,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_ELIQUID_CLOSED_RECHARGABLE_CHEAPEST',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_USD',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '2.55',
  'NumericValue': 2.55,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-11-14T14:50:20+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 40419,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BHS',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2008,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_CURRENCY',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '2.69',
  'NumericValue': 2.69,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-12-15T15:32:59+01:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 40919,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SAU',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2020,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_USD',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '7.47',
  'NumericValue': 7.47,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-12-15T15:32:41+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 46006,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'FRA',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2020,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_PPP',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '13.07',
  'NumericValue': 13.07,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-12-15T15:32:07+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 46809,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SYC',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2022,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_ELIQUID_CLOSED_RECHARGABLE_CHEAPEST',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_PPP',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': None,
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-01-12T12:38:11+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 47225,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DOM',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2022,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_TOBACCO_SMOKELESS_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_CURRENCY',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': None,
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-01-11T16:57:10+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 52460,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'JAM',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2020,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_CURRENCY',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1219',
  'NumericValue': 1219.0,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-12-15T15:32:57+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 52475,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MUS',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2010,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_CURRENCY',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'MUR',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-12-15T15:32:18+01:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 52555,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'HUN',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2022,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_TOBACCO_SMOKELESS_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_PPP',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '19.54',
  'NumericValue': 19.54,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-11-14T14:49:13+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 58836,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KEN',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2022,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_CURRENCY',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'KES',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-12-15T15:31:59+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 58841,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'COL',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2022,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_PREMIUM',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_USD',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1.9',
  'NumericValue': 1.9,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-12-15T17:05:28+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 64977,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DMA',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2016,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_PPP',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '2.35',
  'NumericValue': 2.35,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-12-15T15:31:48+01:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 65880,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SYC',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2022,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_TOBACCO_SMOKELESS_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_USD',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': None,
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-01-11T16:57:09+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 71947,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LUX',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2022,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_TOBACCO_OTHERSMOKED_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_CURRENCY',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '2.35',
  'NumericValue': 2.35,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-11-14T14:48:39+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 72020,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ROU',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2022,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_ELIQUID_OPEN_CHEAPEST',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_CURRENCY',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'RON',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-11-14T14:51:30+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 72237,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'THA',
  'ParentLocationCode': 'SEAR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'South-East Asia',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2018,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD',
  'Dim2Type': 'PRICE',
  'Dim2': 'PRICE_PRICE_IN_CURRENCY',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '60',
  'NumericValue': 60.0,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-12-15T15:33:07+01:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 77502,
  'IndicatorCode': 'TOB_R_PRICE',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SEN',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'TOBACCO_NICOTINE_PRODUCT',
  'TimeDim': 2022,
  'Dim1': 'TOBACCO_NICOTINE_PRODUCT_ELIQUID_OPEN_CHEAPEST',

In [60]:
secondIndicatorDataDataFrame = pd.DataFrame(secondIndicatorData)
secondIndicatorDataDataFrame = secondIndicatorDataDataFrame.loc[secondIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
secondIndicatorDataDataFrame = secondIndicatorDataDataFrame[secondIndicatorDataDataFrame['Dim1'] == 'TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD']
secondIndicatorDataDataFrame = secondIndicatorDataDataFrame[secondIndicatorDataDataFrame['Dim2'] == 'PRICE_PRICE_IN_USD']
secondIndicatorDataDataFrame = secondIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Dim1','Dim2','Value']]
secondIndicatorDataDataFrame

,Id,IndicatorCode,SpatialDim,TimeDim,Dim1,Dim2,Value
40,122023,TOB_R_PRICE,BEL,2008,TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD,PRICE_PRICE_IN_USD,5.79
51,161442,TOB_R_PRICE,LVA,2018,TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD,PRICE_PRICE_IN_USD,4.11
204,621897,TOB_R_PRICE,IRL,2018,TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD,PRICE_PRICE_IN_USD,14.32
221,659841,TOB_R_PRICE,SVN,2012,TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD,PRICE_PRICE_IN_USD,3.58
271,793859,TOB_R_PRICE,LTU,2008,TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD,PRICE_PRICE_IN_USD,2.04
...,...,...,...,...,...,...,...
12467,9259986,TOB_R_PRICE,FRA,2010,TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD,PRICE_PRICE_IN_USD,7.3
12506,9446326,TOB_R_PRICE,BGR,2014,TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD,PRICE_PRICE_IN_USD,3.01
12521,9499630,TOB_R_PRICE,ESP,2014,TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD,PRICE_PRICE_IN_USD,6.42
12542,9592819,TOB_R_PRICE,DEU,2022,TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD,PRICE_PRICE_IN_USD,7.75
12676,10192593,TOB_R_PRICE,POL,2022,TOBACCO_NICOTINE_PRODUCT_CIGARETTE_MOSTSOLD,PRICE_PRICE_IN_USD,3.56

In [61]:
saveToParquet(secondIndicatorDataDataFrame,'mostSoldCigarettePrice')

In [62]:
thirdIndicator = tobaccoIndicatorsDf.iloc[2]
thirdIndicator

IndicatorCode                                         E1_nat_tv_radio
IndicatorName               Ban on advertising: National TV and radio
Language                                                           EN
Category         Tobacco control: Enforce bans on tobacco advertising
Name: 2, dtype: object

In [64]:
thirdIndicatorData = getData(baseURL,thirdIndicator['IndicatorCode'])
thirdIndicatorData = thirdIndicatorData['value']
thirdIndicatorData

[{'Id': 6289190,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'UGA',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2018,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:40:22+01:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 254437,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LTU',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2022,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:41:43+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 6815533,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LCA',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2010,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:41:34+01:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 5297661,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'JAM',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2008,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:42+01:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 8641332,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MCO',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2007,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:55+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 590301,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BRN',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': None,
  'TimeDim': 2012,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:43:29+01:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 9605678,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TKM',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2018,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:39:35+01:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 4373960,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TON',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': None,
  'TimeDim': 2014,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:39:56+01:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 1083202,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GTM',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2016,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:43:36+01:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 9241994,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LAO',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': None,
  'TimeDim': 2008,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:27+01:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 4627218,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'HND',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2018,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:39:12+01:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 6390818,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PAN',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2007,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:43:08+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 4962555,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SGP',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': None,
  'TimeDim': 2007,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:51+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 184876,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SLV',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2016,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:39:01+01:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 1873691,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'NIC',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2008,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:43+01:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 8375678,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BHR',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': None,
  'TimeDim': 2022,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:41:05+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 5410836,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SEN',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2018,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:39:48+01:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 697521,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ARG',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2012,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:13+01:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 10009512,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BWA',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2007,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:51+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 7706327,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'POL',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2008,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:50+01:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 5051170,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LTU',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2010,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:40:40+01:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 3475554,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DZA',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2020,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:39:05+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 5398206,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GBR',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2012,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:41:57+01:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 5442427,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TUV',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': None,
  'TimeDim': 2012,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:41:55+01:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 615532,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LUX',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2010,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:06+01:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 4096217,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'NLD',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2007,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:46+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 9857680,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GMB',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2022,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:41:42+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 2747723,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KGZ',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2012,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:43:39+01:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 4677715,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MLT',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2014,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:40:37+01:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 5139811,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AUS',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': None,
  'TimeDim': 2010,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:40:35+01:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 8432722,
  'IndicatorCode': 'E1_nat_tv_radio',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AUT',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2022,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:40:47+01:00',
  'TimeDimensionValue': '2022',

In [67]:
thirdIndicatorDataDataFrame = pd.DataFrame(thirdIndicatorData)
thirdIndicatorDataDataFrame = thirdIndicatorDataDataFrame[thirdIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
thirdIndicatorDataDataFrame = thirdIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Value']]
thirdIndicatorDataDataFrame

            Id    IndicatorCode SpatialDim  TimeDim Value
1       254437  E1_nat_tv_radio        LTU     2022   Yes
19     7706327  E1_nat_tv_radio        POL     2008   Yes
20     5051170  E1_nat_tv_radio        LTU     2010   Yes
24      615532  E1_nat_tv_radio        LUX     2010   Yes
25     4096217  E1_nat_tv_radio        NLD     2007   Yes
...        ...              ...        ...      ...   ...
1727   9751492  E1_nat_tv_radio        GRC     2010   Yes
1733   9906574  E1_nat_tv_radio        POL     2018   Yes
1736   9994551  E1_nat_tv_radio        BEL     2016   Yes
1753  10192422  E1_nat_tv_radio        CZE     2022   Yes
1754  10204280  E1_nat_tv_radio        LVA     2020   Yes

[243 rows x 5 columns]

In [68]:
saveToParquet(thirdIndicatorDataDataFrame,'TobaccoAdversting')

In [70]:
fourthIndicator = tobaccoIndicatorsDf.iloc[3]
fourthIndicator

IndicatorCode                                          E6a_pt_of_sale
IndicatorName                     Ban on advertising at point of sale
Language                                                           EN
Category         Tobacco control: Enforce bans on tobacco advertising
Name: 3, dtype: object

In [76]:
fourthIndicatorData = getData(baseURL,fourthIndicator['IndicatorCode'])
fourthIndicatorData = fourthIndicatorData['value']
fourthIndicatorData

[{'Id': 7731603,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GTM',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2020,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:40:06+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 7862526,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'COD',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2022,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:41:39+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 3507151,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ERI',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2010,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:41:04+01:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 7256354,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GAB',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2018,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:38:43+01:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 2418289,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CYP',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2008,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:41:49+01:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 1064126,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'UKR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2018,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:40:30+01:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 7617733,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'FIN',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2020,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:38:34+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 7780465,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CZE',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2007,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:24+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 6175541,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LTU',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2014,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:40:06+01:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 4728460,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CUB',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2014,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:39:32+01:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 6891427,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'JOR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': None,
  'TimeDim': 2008,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:26+01:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 8811540,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BEL',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2008,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:43:45+01:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 7786814,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GNQ',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2012,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:41:00+01:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 1405577,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DJI',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': None,
  'TimeDim': 2008,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:41:50+01:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 8185898,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MNG',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': None,
  'TimeDim': 2022,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:41:36+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 5146107,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LSO',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2008,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:23+01:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 8591045,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ARM',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2012,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:39:53+01:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 3855445,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MDA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2007,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:48+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 9493515,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'HTI',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2020,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:40:02+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 4051912,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BOL',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2014,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:40:24+01:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 640641,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SUR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2008,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:09+01:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 9895650,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GTM',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2016,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:43:33+01:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 4487549,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TLS',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'SEAR',
  'ParentLocation': 'South-East Asia',
  'Dim1Type': None,
  'TimeDim': 2007,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:31+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 4810966,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MHL',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': None,
  'TimeDim': 2007,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:43:03+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 6504884,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MYS',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': None,
  'TimeDim': 2022,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:41:33+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 96461,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ARG',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2007,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:42:44+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 8249262,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MHL',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': None,
  'TimeDim': 2016,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:43:23+01:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 8534053,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KGZ',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2010,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:41:57+01:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 8976157,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'VNM',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': None,
  'TimeDim': 2022,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:41:35+01:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 938143,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CPV',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2020,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:38:58+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 7529104,
  'IndicatorCode': 'E6a_pt_of_sale',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BWA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2020,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-31T14:38:49+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',

In [78]:
fourthIndicatorDataDataFrame = pd.DataFrame(fourthIndicatorData)
fourthIndicatorDataDataFrame = fourthIndicatorDataDataFrame[fourthIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
fourthIndicatorDataDataFrame =  fourthIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Value']]
fourthIndicatorDataDataFrame

            Id   IndicatorCode SpatialDim  TimeDim Value
4      2418289  E6a_pt_of_sale        CYP     2008   Yes
6      7617733  E6a_pt_of_sale        FIN     2020   Yes
7      7780465  E6a_pt_of_sale        CZE     2007    No
8      6175541  E6a_pt_of_sale        LTU     2014    No
11     8811540  E6a_pt_of_sale        BEL     2008    No
...        ...             ...        ...      ...   ...
1727   8760288  E6a_pt_of_sale        NLD     2016    No
1729   8874677  E6a_pt_of_sale        MLT     2010   Yes
1730   8918372  E6a_pt_of_sale        CYP     2016   Yes
1748  10008797  E6a_pt_of_sale        SVK     2012    No
1751  10103891  E6a_pt_of_sale        SWE     2012    No

[243 rows x 5 columns]

In [80]:
saveToParquet(fourthIndicatorDataDataFrame,'TobaccoAdverstingPointOnSale')

In [81]:
fifthIndicator = tobaccoIndicatorsDf.iloc[4]
fifthIndicator

IndicatorCode                                             E5_billboards
IndicatorName    Ban on advertising: Billboards and outdoor advertising
Language                                                             EN
Category           Tobacco control: Enforce bans on tobacco advertising
Name: 4, dtype: object

In [83]:
fifthIndicatorData = getData(baseURL,fifthIndicator['IndicatorCode'])
fifthIndicatorData = fifthIndicatorData['value']

In [85]:
fifthIndicatorDataDataFrame = pd.DataFrame(fifthIndicatorData)
fifthIndicatorDataDataFrame = fifthIndicatorDataDataFrame[fifthIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
fifthIndicatorDataDataFrame =  fifthIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Value']]
fifthIndicatorDataDataFrame

           Id  IndicatorCode SpatialDim  TimeDim Value
6     4336126  E5_billboards        FRA     2014   Yes
9     7408645  E5_billboards        IRL     2018   Yes
15    5790671  E5_billboards        FRA     2016   Yes
27    7174383  E5_billboards        SVK     2020   Yes
35    5663953  E5_billboards        MLT     2012   Yes
...       ...            ...        ...      ...   ...
1728  8874657  E5_billboards        GRC     2018   Yes
1732  9032698  E5_billboards        POL     2022   Yes
1734  9140219  E5_billboards        FRA     2008   Yes
1740  9336967  E5_billboards        HUN     2016   Yes
1747  9636406  E5_billboards        NLD     2020   Yes

[243 rows x 5 columns]

In [100]:
saveToParquet(fifthIndicatorDataDataFrame,'TobaccoAdverstingBilboardOutdoorr')

In [90]:
sixthIndicator = tobaccoIndicatorsDf.iloc[5]
sixthIndicatorData = getData(baseURL,sixthIndicator['IndicatorCode'])
sixthIndicatorData = sixthIndicatorData['value']

IndicatorCode                                             E7_internet
IndicatorName                            Ban on advertising: Internet
Language                                                           EN
Category         Tobacco control: Enforce bans on tobacco advertising
Name: 5, dtype: object

In [91]:
sixthIndicatorDataDataFrame = pd.DataFrame(sixthIndicatorData)
sixthIndicatorDataDataFrame = sixthIndicatorDataDataFrame[sixthIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
sixthIndicatorDataDataFrame =  sixthIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Value']]
sixthIndicatorDataDataFrame

           Id IndicatorCode SpatialDim  TimeDim Value
9     6403513   E7_internet        NLD     2012   Yes
17    6821919   E7_internet        DNK     2016   Yes
34    9026887   E7_internet        FRA     2022   Yes
50    1949775   E7_internet        IRL     2012    No
83    2962756   E7_internet        LUX     2010   Yes
...       ...           ...        ...      ...   ...
1723  7900490   E7_internet        ROU     2016   Yes
1724  7912659   E7_internet        DNK     2018   Yes
1725  8071709   E7_internet        LTU     2010   Yes
1743  9434408   E7_internet        BGR     2018   Yes
1747  9636652   E7_internet        SWE     2007    No

[243 rows x 5 columns]

In [93]:
saveToParquet(sixthIndicatorDataDataFrame,'TobaccoAdverstingInternet')

In [97]:
seventhIndicator = tobaccoIndicatorsDf.iloc[6]
seventhIndicatorData = getData(baseURL,seventhIndicator['IndicatorCode'])
seventhIndicatorData = seventhIndicatorData['value']

In [101]:
seventhIndicator

IndicatorCode                                 P6_restaurants
IndicatorName            National smoking ban in RESTAURANTS
Language                                                  EN
Category         Tobacco control: Protect from tobacco smoke
Name: 6, dtype: object

In [98]:
seventhIndicatorDataDataFrame = pd.DataFrame(seventhIndicatorData)
seventhIndicatorDataDataFrame = seventhIndicatorDataDataFrame[seventhIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
seventhIndicatorDataDataFrame =  seventhIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Value']]
seventhIndicatorDataDataFrame

           Id   IndicatorCode SpatialDim  TimeDim Value
8     1285929  P6_restaurants        HRV     2007    No
10    1462460  P6_restaurants        ITA     2018    No
13     102715  P6_restaurants        CYP     2012   Yes
20    7598765  P6_restaurants        ROU     2012    No
30    7085941  P6_restaurants        DEU     2018    No
...       ...             ...        ...      ...   ...
1725  8634903  P6_restaurants        DNK     2014    No
1731  1532042  P6_restaurants        SVN     2014    No
1734  3595798  P6_restaurants        SVN     2018    No
1739  7951422  P6_restaurants        PRT     2022    No
1752  7129887  P6_restaurants        SWE     2022    No

[243 rows x 5 columns]

In [102]:
saveToParquet(seventhIndicatorDataDataFrame,'TobaccoBanInRestaurants')

In [107]:
eightIndicator = tobaccoIndicatorsDf.iloc[7]
eightIndicatorData = getData(baseURL,eightIndicator['IndicatorCode'])
eightIndicatorData = eightIndicatorData['value']
eightIndicatorData

[{'Id': 6390777,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AUT',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2012,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:15:15+02:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 3348773,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SRB',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2022,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:17:01+02:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 1898848,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CPV',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2010,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:16:52+02:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 8438795,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'USA',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2012,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:15:13+02:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 2570463,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'FIN',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2018,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:15:21+02:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 4310809,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MLT',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2016,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:16:52+02:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 7560749,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GMB',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2022,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:17:00+02:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 9267343,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GNB',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2018,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:15:22+02:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 1532150,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ECU',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2020,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:16:54+02:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 9440370,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TUR',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2012,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:16:26+02:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 602961,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SLE',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2014,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:15:07+02:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 4272743,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AFG',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': None,
  'TimeDim': 2010,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:15:58+02:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 203906,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GHA',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2014,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:16:29+02:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 5076336,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BDI',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2016,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:16:57+02:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 8609899,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CYP',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2012,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:15:20+02:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 7142671,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'JPN',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': None,
  'TimeDim': 2010,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:16:29+02:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 5632321,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'FJI',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': None,
  'TimeDim': 2020,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:16:45+02:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 5765288,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'QAT',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': None,
  'TimeDim': 2018,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:15:30+02:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 4153349,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MKD',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2022,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:17:03+02:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 5809728,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SWE',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2010,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:15:04+02:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 4272771,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CZE',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2010,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:15:14+02:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 7693606,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'IRL',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2007,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:15:04+02:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 1627006,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TUR',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'TimeDim': 2016,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:16:43+02:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 3285400,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LSO',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2020,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:16:45+02:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 3412290,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ZMB',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'TimeDim': 2012,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:15:52+02:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 5234855,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'QAT',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': None,
  'TimeDim': 2020,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:16:45+02:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 8540356,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CRI',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2010,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:15:04+02:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 5486781,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PAN',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2012,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:16:22+02:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 7149016,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GUY',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'TimeDim': 2007,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:15:14+02:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 5847401,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'IND',
  'ParentLocationCode': 'SEAR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'South-East Asia',
  'Dim1Type': None,
  'TimeDim': 2014,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:15:07+02:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 9933617,
  'IndicatorCode': 'P8_pub_transp',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PSE',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': None,
  'TimeDim': 2008,
  'Dim1': None,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:15:35+02:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',

In [108]:
eightIndicator

IndicatorCode                                  P8_pub_transp
IndicatorName       National smoking ban in PUBLIC TRANSPORT
Language                                                  EN
Category         Tobacco control: Protect from tobacco smoke
Name: 7, dtype: object

In [109]:
eightIndicatorDataDataFrame = pd.DataFrame(eightIndicatorData)
eightIndicatorDataDataFrame = eightIndicatorDataDataFrame[eightIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
eightIndicatorDataDataFrame =  eightIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Value']]
eightIndicatorDataDataFrame

           Id  IndicatorCode SpatialDim  TimeDim Value
0     6390777  P8_pub_transp        AUT     2012    No
4     2570463  P8_pub_transp        FIN     2018    No
5     4310809  P8_pub_transp        MLT     2016   Yes
14    8609899  P8_pub_transp        CYP     2012    No
19    5809728  P8_pub_transp        SWE     2010    No
...       ...            ...        ...      ...   ...
1657  9825477  P8_pub_transp        ESP     2020   Yes
1675  4297872  P8_pub_transp        POL     2012   Yes
1707   298422  P8_pub_transp        ESP     2012   Yes
1712  2348283  P8_pub_transp        DNK     2022    No
1735   495340  P8_pub_transp        POL     2016   Yes

[243 rows x 5 columns]

In [110]:
saveToParquet(eightIndicatorDataDataFrame,'TobaccoBanINPublicTransport')

In [112]:
ninthIndicator = tobaccoIndicatorsDf.iloc[8]
ninthIndicatorData = getData(baseURL,ninthIndicator['IndicatorCode'])
ninthIndicatorData = ninthIndicatorData['value']
ninthIndicatorData

[{'Id': 4506426,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CRI',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2016,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:45:34+02:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 3013141,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AFG',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2014,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:45:57+02:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 3431311,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ISR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2008,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:46:04+02:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 4026709,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'FJI',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2007,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:46:12+02:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 969791,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MWI',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2020,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:45:59+02:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 9895591,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'COD',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2010,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:46:15+02:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 1121282,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PNG',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2010,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:45:29+02:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 3203091,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CPV',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2010,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:46:03+02:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 8122665,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CAF',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2016,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:46:05+02:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 4937330,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'UZB',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2012,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:46:11+02:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 9451449,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GEO',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2012,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:45:23+02:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 5512176,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'NGA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2014,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:46:13+02:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 747928,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TUR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2022,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:46:30+02:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 773323,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CYP',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2018,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:45:39+02:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 9223199,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'UKR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2008,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:45:31+02:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 7786832,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SWE',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2022,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:46:31+02:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 10186581,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BRB',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2022,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:46:28+02:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 4798228,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'QAT',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2010,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:45:29+02:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 3488187,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BWA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2020,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:45:32+02:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 2132992,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DNK',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2014,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:46:07+02:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 2545093,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BFA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2022,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:46:27+02:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 2627444,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GNB',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2008,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:45:26+02:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 4304540,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'HUN',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2012,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:46:09+02:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 6188285,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PER',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2012,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:45:24+02:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 9292502,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ITA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2012,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': 'Separate enclosed smoking rooms are allowed',
  'Date': '2023-10-17T19:45:53+02:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 343512,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MCO',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2014,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': 'Separate enclosed smoking rooms are allowed',
  'Date': '2023-10-17T19:45:48+02:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 2114207,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ARG',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2016,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:45:58+02:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 552452,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'RUS',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2018,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'Yes',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:45:34+02:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 9662287,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GMB',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2010,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:46:17+02:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 7364241,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AUT',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2010,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:45:29+02:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 5847395,
  'IndicatorCode': 'P5_indoor_off',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GRD',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': None,
  'Dim1': None,
  'TimeDim': 2012,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': 'No',
  'NumericValue': None,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2023-10-17T19:46:24+02:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',

In [113]:
ninthIndicator

IndicatorCode                                  P5_indoor_off
IndicatorName         National smoking ban in INDOOR OFFICES
Language                                                  EN
Category         Tobacco control: Protect from tobacco smoke
Name: 8, dtype: object

In [114]:
ninthIndicatorDataDataFrame = pd.DataFrame(ninthIndicatorData)
ninthIndicatorDataDataFrame = ninthIndicatorDataDataFrame[ninthIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
ninthIndicatorDataDataFrame =  ninthIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Value']]
ninthIndicatorDataDataFrame

           Id  IndicatorCode SpatialDim  TimeDim Value
13     773323  P5_indoor_off        CYP     2018   Yes
15    7786832  P5_indoor_off        SWE     2022    No
19    2132992  P5_indoor_off        DNK     2014    No
22    4304540  P5_indoor_off        HUN     2012   Yes
24    9292502  P5_indoor_off        ITA     2012    No
...       ...            ...        ...      ...   ...
1723  9451323  P5_indoor_off        ROU     2020   Yes
1727  1797496  P5_indoor_off        IRL     2020   Yes
1739  6295465  P5_indoor_off        GRC     2014   Yes
1741  6701234  P5_indoor_off        SVK     2018   Yes
1742  7016415  P5_indoor_off        SWE     2018    No

[243 rows x 5 columns]

In [ ]:
saveToParquet(ninthIndicatorDataDataFrame,'TobaccoBanInIndoorOffices')