In [1]:
import pandas as pd 
import requests
from jsonschema import validate
import json
import fastparquet

In [2]:
pd.set_option('display.width', None)

In [3]:
countriesDf = pd.DataFrame(pd.read_parquet('../dataRawBeforeBlob/countries/euCountriesRaw.parquet'))
countriesDf

,Code,Title,ParentDimension,Dimension,ParentCode,ParentTitle
0,AUT,Austria,REGION,COUNTRY,EUR,Europe
1,BEL,Belgium,REGION,COUNTRY,EUR,Europe
2,BGR,Bulgaria,REGION,COUNTRY,EUR,Europe
3,CYP,Cyprus,REGION,COUNTRY,EUR,Europe
4,CZE,Czechia,REGION,COUNTRY,EUR,Europe
5,DEU,Germany,REGION,COUNTRY,EUR,Europe
6,DNK,Denmark,REGION,COUNTRY,EUR,Europe
7,ESP,Spain,REGION,COUNTRY,EUR,Europe
8,EST,Estonia,REGION,COUNTRY,EUR,Europe
9,FIN,Finland,REGION,COUNTRY,EUR,Europe
10,FRA,France,REGION,COUNTRY,EUR,Europe
11,GRC,Greece,REGION,COUNTRY,EUR,Europe
12,HRV,Croatia,REGION,COUNTRY,EUR,Europe
13,HUN,Hungary,REGION,COUNTRY,EUR,Europe
14,IRL,Ireland,REGION,COUNTRY,EUR,Europe
15,ITA,Italy,REGION,COUNTRY,EUR,Europe
16,LTU,Lithuania,REGION,COUNTRY,EUR,Europe
17,LUX,Luxembourg,REGION,COUNTRY,EUR,Europe
18,LVA,Latvia,REGION,COUNTRY,EUR,Europe
19,MLT,Malta,REGION,COUNTRY,EUR,Europe
20,NLD,Netherlands (Kingdom of the),REGION,COUNTRY,EUR,Europe
21,POL,Poland,REGION,COUNTRY,EUR,Europe
22,PRT,Portugal,REGION,COUNTRY,EUR,Europe
23,ROU,Romania,REGION,COUNTRY,EUR,Europe
24,SVK,Slovakia,REGION,COUNTRY,EUR,Europe
25,SVN,Slovenia,REGION,COUNTRY,EUR,Europe
26,SWE,Sweden,REGION,COUNTRY,EUR,Europe

In [11]:
baseURL= 'https://ghoapi.azureedge.net/api/'

In [7]:
ncdIndicatorsDf = pd.DataFrame(pd.read_parquet('../dataRawBeforeBlob/indicators/ncdIndicators.parquet',engine='fastparquet'))
ncdIndicatorsDf

,IndicatorCode,IndicatorName,Language,Category
0,NCD_CHOL_MEANTOTALCHOL_A,"Mean total cholesterol, age-standardized",EN,NCD: Risk factors and conditions
1,NCD_HYP_PREVALENCE_A,"Hypertension among adults aged 30-79 years, pr...",EN,NCD: Risk factors and conditions
2,NCD_DIABETES_PREVALENCE_AGESTD,"Prevalence of diabetes, age-standardized",EN,NCD: Risk factors and conditions
3,WHS2_131,Age-standardized NCD mortality rate (per 100 ...,EN,NCD: Mortality
4,NCD_DTH_TOT,Total NCD Deaths,EN,NCD: Mortality
5,NCDMORT3070,Probability (%) of dying between age 30 and ex...,EN,NCD: Mortality

In [8]:
def getData(baseurl,indicatorCode:str):
    indicatorCode = indicatorCode.strip()
    response = requests.get(baseurl+f"{indicatorCode}")
    if response.status_code == 200 and response.headers.get('Content-Type').startswith('application/json') :
        return response.json()
    else:
        return 'Something went wrong with request'

In [36]:
def saveToParquet(df: pd.DataFrame,filename:str):
    df.to_parquet(f'../dataRawBeforeBlob/ncdData/{filename}.parquet',engine='fastparquet')

In [10]:
firstIndicator = ncdIndicatorsDf.iloc[0]
firstIndicator

IndicatorCode                     NCD_CHOL_MEANTOTALCHOL_A
IndicatorName    Mean total cholesterol,  age-standardized
Language                                                EN
Category                  NCD: Risk factors and conditions
Name: 0, dtype: object

In [23]:
firstIndicatorData = getData(baseURL,firstIndicator['IndicatorCode'])
firstIndicatorData = firstIndicatorData['value']

firstIndicatorData

[{'Id': 9455120,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TTO',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2006,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.5 [4.0-5.0]',
  'NumericValue': 4.5,
  'Low': 4.0,
  'High': 5.0,
  'Comments': None,
  'Date': '2021-06-21T18:29:13+02:00',
  'TimeDimensionValue': '2006',
  'TimeDimensionBegin': '2006-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2006-12-31T00:00:00+01:00'},
 {'Id': 9455336,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MRT',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 1990,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.1 [3.6-4.5]',
  'NumericValue': 4.1,
  'Low': 3.6,
  'High': 4.5,
  'Comments': None,
  'Date': '2021-06-21T18:27:57+02:00',
  'TimeDimensionValue': '1990',
  'TimeDimensionBegin': '1990-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1990-12-31T00:00:00+01:00'},
 {'Id': 9455714,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TUN',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 1996,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.7 [4.5-4.9]',
  'NumericValue': 4.7,
  'Low': 4.5,
  'High': 4.9,
  'Comments': None,
  'Date': '2021-06-21T18:49:33+02:00',
  'TimeDimensionValue': '1996',
  'TimeDimensionBegin': '1996-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1996-12-31T00:00:00+01:00'},
 {'Id': 163,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GNB',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2009,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.1 [3.7-4.5]',
  'NumericValue': 4.1,
  'Low': 3.7,
  'High': 4.5,
  'Comments': None,
  'Date': '2021-06-21T18:47:32+02:00',
  'TimeDimensionValue': '2009',
  'TimeDimensionBegin': '2009-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2009-12-31T00:00:00+01:00'},
 {'Id': 380,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CPV',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 1990,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '3.8 [3.4-4.2]',
  'NumericValue': 3.8,
  'Low': 3.4,
  'High': 4.2,
  'Comments': None,
  'Date': '2021-06-21T18:26:33+02:00',
  'TimeDimensionValue': '1990',
  'TimeDimensionBegin': '1990-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1990-12-31T00:00:00+01:00'},
 {'Id': 1212,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GMB',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 1980,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '3.9 [3.2-4.6]',
  'NumericValue': 3.9,
  'Low': 3.2,
  'High': 4.6,
  'Comments': None,
  'Date': '2021-06-21T18:27:12+02:00',
  'TimeDimensionValue': '1980',
  'TimeDimensionBegin': '1980-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1980-12-31T00:00:00+01:00'},
 {'Id': 1746,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'REGION',
  'SpatialDim': 'EMR',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 2003,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.5 [4.4-4.6]',
  'NumericValue': 4.5,
  'Low': 4.4,
  'High': 4.6,
  'Comments': None,
  'Date': '2021-06-21T17:36:45+02:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 1962,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AFG',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2009,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.3 [3.9-4.7]',
  'NumericValue': 4.3,
  'Low': 3.9,
  'High': 4.7,
  'Comments': None,
  'Date': '2021-06-21T18:44:56+02:00',
  'TimeDimensionValue': '2009',
  'TimeDimensionBegin': '2009-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2009-12-31T00:00:00+01:00'},
 {'Id': 2613,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AND',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2007,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '5.2 [4.8-5.7]',
  'NumericValue': 5.2,
  'Low': 4.8,
  'High': 5.7,
  'Comments': None,
  'Date': '2021-06-21T18:26:04+02:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 2841,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'JOR',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 1982,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.8 [4.2-5.3]',
  'NumericValue': 4.8,
  'Low': 4.2,
  'High': 5.3,
  'Comments': None,
  'Date': '2021-06-21T18:27:34+02:00',
  'TimeDimensionValue': '1982',
  'TimeDimensionBegin': '1982-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1982-12-31T00:00:00+01:00'},
 {'Id': 2965,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SLB',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 1989,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.5 [4.1-4.9]',
  'NumericValue': 4.5,
  'Low': 4.1,
  'High': 4.9,
  'Comments': None,
  'Date': '2021-06-21T18:28:50+02:00',
  'TimeDimensionValue': '1989',
  'TimeDimensionBegin': '1989-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1989-12-31T00:00:00+01:00'},
 {'Id': 3678,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AZE',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 1988,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.5 [4.0-5.0]',
  'NumericValue': 4.5,
  'Low': 4.0,
  'High': 5.0,
  'Comments': None,
  'Date': '2021-06-21T18:26:11+02:00',
  'TimeDimensionValue': '1988',
  'TimeDimensionBegin': '1988-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1988-12-31T00:00:00+01:00'},
 {'Id': 3955,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GBR',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2009,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '5.2 [5.1-5.3]',
  'NumericValue': 5.2,
  'Low': 5.1,
  'High': 5.3,
  'Comments': None,
  'Date': '2021-06-21T18:49:39+02:00',
  'TimeDimensionValue': '2009',
  'TimeDimensionBegin': '2009-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2009-12-31T00:00:00+01:00'},
 {'Id': 4043,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SRB',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2009,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '5.3 [5.1-5.5]',
  'NumericValue': 5.3,
  'Low': 5.1,
  'High': 5.5,
  'Comments': None,
  'Date': '2021-06-21T19:03:30+02:00',
  'TimeDimensionValue': '2009',
  'TimeDimensionBegin': '2009-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2009-12-31T00:00:00+01:00'},
 {'Id': 4121,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SWZ',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 1981,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '3.9 [3.5-4.4]',
  'NumericValue': 3.9,
  'Low': 3.5,
  'High': 4.4,
  'Comments': None,
  'Date': '2021-06-21T19:01:20+02:00',
  'TimeDimensionValue': '1981',
  'TimeDimensionBegin': '1981-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1981-12-31T00:00:00+01:00'},
 {'Id': 4535,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GAB',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 1999,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.3 [3.9-4.7]',
  'NumericValue': 4.3,
  'Low': 3.9,
  'High': 4.7,
  'Comments': None,
  'Date': '2021-06-21T19:02:43+02:00',
  'TimeDimensionValue': '1999',
  'TimeDimensionBegin': '1999-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1999-12-31T00:00:00+01:00'},
 {'Id': 4545,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'WORLDBANKINCOMEGROUP',
  'SpatialDim': 'WB_LMI',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 2013,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.4 [4.3-4.4]',
  'NumericValue': 4.4,
  'Low': 4.3,
  'High': 4.4,
  'Comments': None,
  'Date': '2021-06-21T18:18:03+02:00',
  'TimeDimensionValue': '2013',
  'TimeDimensionBegin': '2013-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2013-12-31T00:00:00+01:00'},
 {'Id': 4585,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'JPN',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 2007,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '5.0 [4.9-5.1]',
  'NumericValue': 5.0,
  'Low': 4.9,
  'High': 5.1,
  'Comments': None,
  'Date': '2021-06-21T18:47:46+02:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 6513,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'WORLDBANKINCOMEGROUP',
  'SpatialDim': 'WB_HI',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 2004,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '5.1 [5.0-5.1]',
  'NumericValue': 5.1,
  'Low': 5.0,
  'High': 5.1,
  'Comments': None,
  'Date': '2021-06-21T18:18:02+02:00',
  'TimeDimensionValue': '2004',
  'TimeDimensionBegin': '2004-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2004-12-31T00:00:00+01:00'},
 {'Id': 7079,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SLE',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 1991,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '3.8 [3.3-4.3]',
  'NumericValue': 3.8,
  'Low': 3.3,
  'High': 4.3,
  'Comments': None,
  'Date': '2021-06-21T18:28:44+02:00',
  'TimeDimensionValue': '1991',
  'TimeDimensionBegin': '1991-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1991-12-31T00:00:00+01:00'},
 {'Id': 7351,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LBN',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 1986,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '5.0 [4.7-5.4]',
  'NumericValue': 5.0,
  'Low': 4.7,
  'High': 5.4,
  'Comments': None,
  'Date': '2021-06-21T19:01:43+02:00',
  'TimeDimensionValue': '1986',
  'TimeDimensionBegin': '1986-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1986-12-31T00:00:00+01:00'},
 {'Id': 8225,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PHL',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 1985,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.7 [4.2-5.1]',
  'NumericValue': 4.7,
  'Low': 4.2,
  'High': 5.1,
  'Comments': None,
  'Date': '2021-06-21T18:48:40+02:00',
  'TimeDimensionValue': '1985',
  'TimeDimensionBegin': '1985-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1985-12-31T00:00:00+01:00'},
 {'Id': 9686,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MLT',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 1995,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '5.6 [5.2-6.0]',
  'NumericValue': 5.6,
  'Low': 5.2,
  'High': 6.0,
  'Comments': None,
  'Date': '2021-06-21T18:27:55+02:00',
  'TimeDimensionValue': '1995',
  'TimeDimensionBegin': '1995-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1995-12-31T00:00:00+01:00'},
 {'Id': 9787,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DZA',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 1989,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.4 [4.0-4.7]',
  'NumericValue': 4.4,
  'Low': 4.0,
  'High': 4.7,
  'Comments': None,
  'Date': '2021-06-21T18:26:03+02:00',
  'TimeDimensionValue': '1989',
  'TimeDimensionBegin': '1989-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1989-12-31T00:00:00+01:00'},
 {'Id': 9842,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'UZB',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 1995,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.3 [3.9-4.7]',
  'NumericValue': 4.3,
  'Low': 3.9,
  'High': 4.7,
  'Comments': None,
  'Date': '2021-06-21T18:29:27+02:00',
  'TimeDimensionValue': '1995',
  'TimeDimensionBegin': '1995-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1995-12-31T00:00:00+01:00'},
 {'Id': 9918,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PAK',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2008,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.3 [4.1-4.5]',
  'NumericValue': 4.3,
  'Low': 4.1,
  'High': 4.5,
  'Comments': None,
  'Date': '2021-06-21T19:03:25+02:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 10059,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'UGA',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 1991,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '3.8 [3.5-4.1]',
  'NumericValue': 3.8,
  'Low': 3.5,
  'High': 4.1,
  'Comments': None,
  'Date': '2021-06-21T19:02:10+02:00',
  'TimeDimensionValue': '1991',
  'TimeDimensionBegin': '1991-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1991-12-31T00:00:00+01:00'},
 {'Id': 10224,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GRD',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 1992,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.5 [4.1-5.0]',
  'NumericValue': 4.5,
  'Low': 4.1,
  'High': 5.0,
  'Comments': None,
  'Date': '2021-06-21T18:47:28+02:00',
  'TimeDimensionValue': '1992',
  'TimeDimensionBegin': '1992-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1992-12-31T00:00:00+01:00'},
 {'Id': 10455,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CIV',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 1997,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.1 [3.6-4.6]',
  'NumericValue': 4.1,
  'Low': 3.6,
  'High': 4.6,
  'Comments': None,
  'Date': '2021-06-21T18:46:08+02:00',
  'TimeDimensionValue': '1997',
  'TimeDimensionBegin': '1997-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1997-12-31T00:00:00+01:00'},
 {'Id': 10588,
  'IndicatorCode': 'NCD_CHOL_MEANTOTALCHOL_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'POL',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 1985,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '5.3 [5.1-5.5]',
  'NumericValue': 5.3,
  'Low': 5.1,
  'High': 5.5,
  'Comments': None,
  'Date': '2021-06-21T18:28:27+02:00',
  'TimeDimensionValue': '1985',

In [16]:
firstIndicatorDataDataFrame = pd.DataFrame(firstIndicatorData)
firstIndicatorDataDataFrame = firstIndicatorDataDataFrame.loc[firstIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
firstIndicatorDataDataFrame = firstIndicatorDataDataFrame.loc[firstIndicatorDataDataFrame['Dim1'] == 'SEX_BTSX']
firstIndicatorDataDataFrame['Value'] = firstIndicatorDataDataFrame['Value'].astype('string')
firstIndicatorDataDataFrame['Value'] = firstIndicatorDataDataFrame['Value'].str.split(' ').str[0]
firstIndicatorDataDataFrame['Value'] = firstIndicatorDataDataFrame['Value'].astype('float')
firstIndicatorDataDataFrame = firstIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Dim1','Value']]
firstIndicatorDataDataFrame

             Id             IndicatorCode SpatialDim  TimeDim      Dim1  Value
46        20433  NCD_CHOL_MEANTOTALCHOL_A        AUT     1997  SEX_BTSX    5.6
108       48406  NCD_CHOL_MEANTOTALCHOL_A        LTU     2004  SEX_BTSX    5.5
188       82381  NCD_CHOL_MEANTOTALCHOL_A        ITA     2006  SEX_BTSX    5.2
217       96321  NCD_CHOL_MEANTOTALCHOL_A        DEU     2018  SEX_BTSX    4.9
218       98062  NCD_CHOL_MEANTOTALCHOL_A        POL     2018  SEX_BTSX    4.9
...         ...                       ...        ...      ...       ...    ...
23534  10168983  NCD_CHOL_MEANTOTALCHOL_A        NLD     2008  SEX_BTSX    5.0
23536  10169626  NCD_CHOL_MEANTOTALCHOL_A        FRA     2009  SEX_BTSX    5.2
23546  10174045  NCD_CHOL_MEANTOTALCHOL_A        HRV     1990  SEX_BTSX    5.5
23559  10177994  NCD_CHOL_MEANTOTALCHOL_A        CYP     1995  SEX_BTSX    5.4
23566  10180140  NCD_CHOL_MEANTOTALCHOL_A        CYP     1984  SEX_BTSX    5.6

[1053 rows x 6 columns]

In [39]:
saveToParquet(firstIndicatorDataDataFrame,'ncdCholesterol')

In [18]:
secondIndicator = ncdIndicatorsDf.iloc[1]
secondIndicator

IndicatorCode                                 NCD_HYP_PREVALENCE_A
IndicatorName    Hypertension among adults aged 30-79 years, pr...
Language                                                        EN
Category                          NCD: Risk factors and conditions
Name: 1, dtype: object

In [19]:
secondIndicatorData = getData(baseURL,secondIndicator['IndicatorCode'])
secondIndicatorData = secondIndicatorData['value']
secondIndicatorData

[{'Id': 9455017,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'VEN',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2014,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '40.4 [33.7-47.5]',
  'NumericValue': 40.4,
  'Low': 33.7,
  'High': 47.5,
  'Comments': None,
  'Date': '2021-08-20T16:07:55+02:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 1558,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'UKR',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2003,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '50.0 [43.9-55.9]',
  'NumericValue': 50.0,
  'Low': 43.9,
  'High': 55.9,
  'Comments': None,
  'Date': '2021-08-20T16:05:04+02:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 2582,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'VNM',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 2018,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '29.5 [24.2-35.2]',
  'NumericValue': 29.5,
  'Low': 24.2,
  'High': 35.2,
  'Comments': None,
  'Date': '2021-08-20T16:08:15+02:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 2702,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KAZ',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2011,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '40.2 [32.4-48.5]',
  'NumericValue': 40.2,
  'Low': 32.4,
  'High': 48.5,
  'Comments': None,
  'Date': '2021-08-20T15:38:44+02:00',
  'TimeDimensionValue': '2011',
  'TimeDimensionBegin': '2011-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2011-12-31T00:00:00+01:00'},
 {'Id': 3065,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SGP',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 2003,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '37.6 [32.5-43.2]',
  'NumericValue': 37.6,
  'Low': 32.5,
  'High': 43.2,
  'Comments': None,
  'Date': '2021-08-20T15:57:17+02:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 4292,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GNQ',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2003,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '38.2 [28.5-48.5]',
  'NumericValue': 38.2,
  'Low': 28.5,
  'High': 48.5,
  'Comments': None,
  'Date': '2021-08-20T15:29:06+02:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 4458,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CYP',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2019,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '35.7 [22.5-50.7]',
  'NumericValue': 35.7,
  'Low': 22.5,
  'High': 50.7,
  'Comments': None,
  'Date': '2021-08-20T15:26:03+02:00',
  'TimeDimensionValue': '2019',
  'TimeDimensionBegin': '2019-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2019-12-31T00:00:00+01:00'},
 {'Id': 4699,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KAZ',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 1996,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '39.4 [31.1-47.9]',
  'NumericValue': 39.4,
  'Low': 31.1,
  'High': 47.9,
  'Comments': None,
  'Date': '2021-08-20T15:38:42+02:00',
  'TimeDimensionValue': '1996',
  'TimeDimensionBegin': '1996-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1996-12-31T00:00:00+01:00'},
 {'Id': 4922,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'WORLDBANKINCOMEGROUP',
  'SpatialDim': 'WB_UMI',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 1996,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '30.9 [29.5-32.3]',
  'NumericValue': 30.9,
  'Low': 29.5,
  'High': 32.3,
  'Comments': None,
  'Date': '2021-08-20T15:03:07+02:00',
  'TimeDimensionValue': '1996',
  'TimeDimensionBegin': '1996-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1996-12-31T00:00:00+01:00'},
 {'Id': 4974,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ROU',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 1998,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '48.7 [38.2-59.4]',
  'NumericValue': 48.7,
  'Low': 38.2,
  'High': 59.4,
  'Comments': None,
  'Date': '2021-08-20T15:53:50+02:00',
  'TimeDimensionValue': '1998',
  'TimeDimensionBegin': '1998-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1998-12-31T00:00:00+01:00'},
 {'Id': 5458,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'VCT',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2008,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '38.7 [32.8-44.7]',
  'NumericValue': 38.7,
  'Low': 32.8,
  'High': 44.7,
  'Comments': None,
  'Date': '2021-08-20T15:55:10+02:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 5518,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SYC',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2001,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '47.7 [43.1-52.3]',
  'NumericValue': 47.7,
  'Low': 43.1,
  'High': 52.3,
  'Comments': None,
  'Date': '2021-08-20T15:56:44+02:00',
  'TimeDimensionValue': '2001',
  'TimeDimensionBegin': '2001-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2001-12-31T00:00:00+01:00'},
 {'Id': 5610,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SRB',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2006,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '46.0 [42.2-49.8]',
  'NumericValue': 46.0,
  'Low': 42.2,
  'High': 49.8,
  'Comments': None,
  'Date': '2021-08-20T15:56:29+02:00',
  'TimeDimensionValue': '2006',
  'TimeDimensionBegin': '2006-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2006-12-31T00:00:00+01:00'},
 {'Id': 6369,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'UZB',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2016,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '43.3 [37.4-49.2]',
  'NumericValue': 43.3,
  'Low': 37.4,
  'High': 49.2,
  'Comments': None,
  'Date': '2021-08-20T16:07:11+02:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 6497,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LBN',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 1990,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '39.2 [25.1-54.3]',
  'NumericValue': 39.2,
  'Low': 25.1,
  'High': 54.3,
  'Comments': None,
  'Date': '2021-08-20T15:40:39+02:00',
  'TimeDimensionValue': '1990',
  'TimeDimensionBegin': '1990-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1990-12-31T00:00:00+01:00'},
 {'Id': 6925,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CHL',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 1996,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '38.2 [32.2-44.6]',
  'NumericValue': 38.2,
  'Low': 32.2,
  'High': 44.6,
  'Comments': None,
  'Date': '2021-08-20T15:23:16+02:00',
  'TimeDimensionValue': '1996',
  'TimeDimensionBegin': '1996-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1996-12-31T00:00:00+01:00'},
 {'Id': 6947,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SOM',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2001,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '37.6 [26.6-49.4]',
  'NumericValue': 37.6,
  'Low': 26.6,
  'High': 49.4,
  'Comments': None,
  'Date': '2021-08-20T15:58:19+02:00',
  'TimeDimensionValue': '2001',
  'TimeDimensionBegin': '2001-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2001-12-31T00:00:00+01:00'},
 {'Id': 7463,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CZE',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 1993,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '40.7 [36.3-44.9]',
  'NumericValue': 40.7,
  'Low': 36.3,
  'High': 44.9,
  'Comments': None,
  'Date': '2021-08-20T15:26:18+02:00',
  'TimeDimensionValue': '1993',
  'TimeDimensionBegin': '1993-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1993-12-31T00:00:00+01:00'},
 {'Id': 7498,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'NPL',
  'ParentLocationCode': 'SEAR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'South-East Asia',
  'Dim1Type': 'SEX',
  'TimeDim': 2015,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '39.3 [35.0-43.6]',
  'NumericValue': 39.3,
  'Low': 35.0,
  'High': 43.6,
  'Comments': None,
  'Date': '2021-08-20T15:47:15+02:00',
  'TimeDimensionValue': '2015',
  'TimeDimensionBegin': '2015-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2015-12-31T00:00:00+01:00'},
 {'Id': 7691,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'NIU',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 2018,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '39.2 [28.0-51.5]',
  'NumericValue': 39.2,
  'Low': 28.0,
  'High': 51.5,
  'Comments': None,
  'Date': '2021-08-20T15:48:54+02:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 8130,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GEO',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 1997,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '40.9 [30.5-51.2]',
  'NumericValue': 40.9,
  'Low': 30.5,
  'High': 51.2,
  'Comments': None,
  'Date': '2021-08-20T15:32:20+02:00',
  'TimeDimensionValue': '1997',
  'TimeDimensionBegin': '1997-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1997-12-31T00:00:00+01:00'},
 {'Id': 8542,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'UNSDGREGION',
  'SpatialDim': 'UNSDG_CENTRALASIASOUTHERNASIA',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 1997,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '31.2 [28.2-34.3]',
  'NumericValue': 31.2,
  'Low': 28.2,
  'High': 34.3,
  'Comments': None,
  'Date': '2021-08-20T15:06:58+02:00',
  'TimeDimensionValue': '1997',
  'TimeDimensionBegin': '1997-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1997-12-31T00:00:00+01:00'},
 {'Id': 9047,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AUT',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2001,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '44.5 [35.4-53.8]',
  'NumericValue': 44.5,
  'Low': 35.4,
  'High': 53.8,
  'Comments': None,
  'Date': '2021-08-20T15:16:18+02:00',
  'TimeDimensionValue': '2001',
  'TimeDimensionBegin': '2001-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2001-12-31T00:00:00+01:00'},
 {'Id': 9500,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'STP',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2005,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '46.5 [38.2-55.1]',
  'NumericValue': 46.5,
  'Low': 38.2,
  'High': 55.1,
  'Comments': None,
  'Date': '2021-08-20T15:55:42+02:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 10102,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ARE',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 1992,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '35.8 [24.2-48.4]',
  'NumericValue': 35.8,
  'Low': 24.2,
  'High': 48.4,
  'Comments': None,
  'Date': '2021-08-20T16:05:25+02:00',
  'TimeDimensionValue': '1992',
  'TimeDimensionBegin': '1992-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1992-12-31T00:00:00+01:00'},
 {'Id': 11484,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LBN',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2016,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '38.6 [33.9-43.4]',
  'NumericValue': 38.6,
  'Low': 33.9,
  'High': 43.4,
  'Comments': None,
  'Date': '2021-08-20T15:40:38+02:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 12134,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SSD',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 1999,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '35.6 [26.9-44.9]',
  'NumericValue': 35.6,
  'Low': 26.9,
  'High': 44.9,
  'Comments': None,
  'Date': '2021-08-20T15:58:49+02:00',
  'TimeDimensionValue': '1999',
  'TimeDimensionBegin': '1999-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1999-12-31T00:00:00+01:00'},
 {'Id': 12292,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'WORLDBANKINCOMEGROUP',
  'SpatialDim': 'WB_UMI',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 1995,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '30.3 [28.4-32.2]',
  'NumericValue': 30.3,
  'Low': 28.4,
  'High': 32.2,
  'Comments': None,
  'Date': '2021-08-20T15:02:47+02:00',
  'TimeDimensionValue': '1995',
  'TimeDimensionBegin': '1995-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1995-12-31T00:00:00+01:00'},
 {'Id': 13072,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'WORLDBANKINCOMEGROUP',
  'SpatialDim': 'WB_LI',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 2004,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '34.8 [32.9-36.7]',
  'NumericValue': 34.8,
  'Low': 32.9,
  'High': 36.7,
  'Comments': None,
  'Date': '2021-08-20T15:03:07+02:00',
  'TimeDimensionValue': '2004',
  'TimeDimensionBegin': '2004-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2004-12-31T00:00:00+01:00'},
 {'Id': 13191,
  'IndicatorCode': 'NCD_HYP_PREVALENCE_A',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'NER',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2002,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '43.6 [34.2-53.4]',
  'NumericValue': 43.6,
  'Low': 34.2,
  'High': 53.4,
  'Comments': None,

In [20]:
secondIndicatorDataDataFrame = pd.DataFrame(secondIndicatorData)
secondIndicatorDataDataFrame = secondIndicatorDataDataFrame.loc[secondIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
secondIndicatorDataDataFrame = secondIndicatorDataDataFrame.loc[secondIndicatorDataDataFrame['Dim1'] == 'SEX_BTSX']
secondIndicatorDataDataFrame['Value'] = secondIndicatorDataDataFrame['Value'].astype('string')
secondIndicatorDataDataFrame['Value'] = secondIndicatorDataDataFrame['Value'].str.split(' ').str[0]
secondIndicatorDataDataFrame['Value'] = secondIndicatorDataDataFrame['Value'].astype('float')
secondIndicatorDataDataFrame = secondIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Dim1','Value']]
secondIndicatorDataDataFrame

             Id         IndicatorCode SpatialDim  TimeDim      Dim1  Value
34        14847  NCD_HYP_PREVALENCE_A        IRL     2002  SEX_BTSX   36.4
50        23641  NCD_HYP_PREVALENCE_A        SWE     2019  SEX_BTSX   30.2
64        28906  NCD_HYP_PREVALENCE_A        CYP     2009  SEX_BTSX   34.3
120       55148  NCD_HYP_PREVALENCE_A        SVN     1991  SEX_BTSX   47.4
139       66433  NCD_HYP_PREVALENCE_A        POL     2012  SEX_BTSX   47.3
...         ...                   ...        ...      ...       ...    ...
19206  10192284  NCD_HYP_PREVALENCE_A        EST     2011  SEX_BTSX   41.8
19208  10194150  NCD_HYP_PREVALENCE_A        LUX     2016  SEX_BTSX   32.8
19212  10196554  NCD_HYP_PREVALENCE_A        FIN     2006  SEX_BTSX   40.2
19220  10201077  NCD_HYP_PREVALENCE_A        ESP     2005  SEX_BTSX   35.3
19223  10202987  NCD_HYP_PREVALENCE_A        FRA     2006  SEX_BTSX   33.0

[810 rows x 6 columns]

In [40]:
saveToParquet(secondIndicatorDataDataFrame,'ncdHypertension')

In [21]:
thirdIndicator = ncdIndicatorsDf.iloc[2]
thirdIndicator

IndicatorCode              NCD_DIABETES_PREVALENCE_AGESTD
IndicatorName    Prevalence of diabetes, age-standardized
Language                                               EN
Category                 NCD: Risk factors and conditions
Name: 2, dtype: object

In [22]:
thirdIndicatorData = getData(baseURL,thirdIndicator['IndicatorCode'])
thirdIndicatorData = thirdIndicatorData['value']
thirdIndicatorData

[{'Id': 9455041,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AFG',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2003,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS18-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '13.6 [6.5-23.1]',
  'NumericValue': 13.594753,
  'Low': 6.4873122,
  'High': 23.0599,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 9455103,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SOM',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2016,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '11.5 [5.5-19.6]',
  'NumericValue': 11.497972,
  'Low': 5.5167533,
  'High': 19.555771,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 9455401,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TKM',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2009,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '23.4 [15.7-32.1]',
  'NumericValue': 23.408471,
  'Low': 15.742287,
  'High': 32.128412,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2009',
  'TimeDimensionBegin': '2009-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2009-12-31T00:00:00+01:00'},
 {'Id': 9455521,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KEN',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2005,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '7.8 [3.5-13.9]',
  'NumericValue': 7.756532,
  'Low': 3.4761842,
  'High': 13.892537,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 28,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PRY',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2007,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS18-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '10.0 [5.3-16.3]',
  'NumericValue': 9.9503644,
  'Low': 5.3250771,
  'High': 16.260022,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 249,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SGP',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2006,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '15.9 [13.2-18.8]',
  'NumericValue': 15.900119,
  'Low': 13.187128,
  'High': 18.786639,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2006',
  'TimeDimensionBegin': '2006-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2006-12-31T00:00:00+01:00'},
 {'Id': 320,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MHL',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 1999,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '43.3 [33.8-53.0]',
  'NumericValue': 43.280262,
  'Low': 33.752736,
  'High': 52.951056,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '1999',
  'TimeDimensionBegin': '1999-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1999-12-31T00:00:00+01:00'},
 {'Id': 593,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MRT',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 1996,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '8.0 [4.5-12.6]',
  'NumericValue': 8.0131449,
  'Low': 4.5205742,
  'High': 12.588623,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '1996',
  'TimeDimensionBegin': '1996-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1996-12-31T00:00:00+01:00'},
 {'Id': 613,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ESP',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 1998,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '8.7 [7.0-10.7]',
  'NumericValue': 8.7407701,
  'Low': 6.970799,
  'High': 10.694166,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '1998',
  'TimeDimensionBegin': '1998-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1998-12-31T00:00:00+01:00'},
 {'Id': 959,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LTU',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2002,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS18-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '7.2 [4.7-10.4]',
  'NumericValue': 7.2361439,
  'Low': 4.743496,
  'High': 10.403345,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2002',
  'TimeDimensionBegin': '2002-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2002-12-31T00:00:00+01:00'},
 {'Id': 991,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PRK',
  'ParentLocationCode': 'SEAR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'South-East Asia',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 1990,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS18-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '6.7 [2.1-14.5]',
  'NumericValue': 6.7289539,
  'Low': 2.1189103,
  'High': 14.475568,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '1990',
  'TimeDimensionBegin': '1990-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1990-12-31T00:00:00+01:00'},
 {'Id': 1094,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CPV',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 1997,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS18-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '7.8 [3.8-13.6]',
  'NumericValue': 7.816007,
  'Low': 3.8287695,
  'High': 13.64204,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '1997',
  'TimeDimensionBegin': '1997-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1997-12-31T00:00:00+01:00'},
 {'Id': 1586,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'HND',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2001,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS18-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '7.9 [3.7-13.7]',
  'NumericValue': 7.8836977,
  'Low': 3.7416156,
  'High': 13.686857,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2001',
  'TimeDimensionBegin': '2001-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2001-12-31T00:00:00+01:00'},
 {'Id': 1639,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'UGA',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2014,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '5.9 [3.5-8.9]',
  'NumericValue': 5.8558315,
  'Low': 3.5205755,
  'High': 8.9219779,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 1800,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'IDN',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2004,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS18-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '5.3 [3.8-7.0]',
  'NumericValue': 5.2981138,
  'Low': 3.7877616,
  'High': 7.0383534,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2004',
  'TimeDimensionBegin': '2004-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2004-12-31T00:00:00+01:00'},
 {'Id': 2234,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'REGION',
  'SpatialDim': 'AFR',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2010,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS18-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '8.7 [7.9-9.5]',
  'NumericValue': 8.6737141,
  'Low': 7.8571148,
  'High': 9.539593,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 2632,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AZE',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2013,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '12.7 [7.7-19.2]',
  'NumericValue': 12.725972,
  'Low': 7.7024221,
  'High': 19.215459,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2013',
  'TimeDimensionBegin': '2013-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2013-12-31T00:00:00+01:00'},
 {'Id': 3122,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ARM',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2012,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS18-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '9.0 [5.4-13.5]',
  'NumericValue': 9.0321317,
  'Low': 5.3914193,
  'High': 13.503559,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 3326,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LBN',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2013,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '21.5 [16.8-26.6]',
  'NumericValue': 21.47032,
  'Low': 16.779387,
  'High': 26.608533,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2013',
  'TimeDimensionBegin': '2013-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2013-12-31T00:00:00+01:00'},
 {'Id': 3620,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ROU',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 1994,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.8 [2.8-7.5]',
  'NumericValue': 4.8031345,
  'Low': 2.8411895,
  'High': 7.4635111,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '1994',
  'TimeDimensionBegin': '1994-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1994-12-31T00:00:00+01:00'},
 {'Id': 3755,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AZE',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 1990,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS18-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '6.8 [2.4-14.2]',
  'NumericValue': 6.8220906,
  'Low': 2.3591692,
  'High': 14.165355,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '1990',
  'TimeDimensionBegin': '1990-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1990-12-31T00:00:00+01:00'},
 {'Id': 4849,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'REGION',
  'SpatialDim': 'EMR',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 1993,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS18-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '10.8 [8.8-13.0]',
  'NumericValue': 10.775083,
  'Low': 8.7968856,
  'High': 12.974153,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '1993',
  'TimeDimensionBegin': '1993-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1993-12-31T00:00:00+01:00'},
 {'Id': 4933,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LBN',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 1994,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS18-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '11.3 [5.3-19.9]',
  'NumericValue': 11.348072,
  'Low': 5.3485889,
  'High': 19.904196,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '1994',
  'TimeDimensionBegin': '1994-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1994-12-31T00:00:00+01:00'},
 {'Id': 5429,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ROU',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2002,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '5.1 [3.7-6.7]',
  'NumericValue': 5.0541464,
  'Low': 3.7453659,
  'High': 6.6840596,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2002',
  'TimeDimensionBegin': '2002-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2002-12-31T00:00:00+01:00'},
 {'Id': 5489,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'RWA',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2009,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '5.1 [2.8-8.2]',
  'NumericValue': 5.0588228,
  'Low': 2.7572254,
  'High': 8.1761986,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2009',
  'TimeDimensionBegin': '2009-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2009-12-31T00:00:00+01:00'},
 {'Id': 5558,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SRB',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2018,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS18-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '8.2 [2.9-17.1]',
  'NumericValue': 8.2336478,
  'Low': 2.8667228,
  'High': 17.123999,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 5917,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KGZ',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 1992,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '9.2 [4.7-15.4]',
  'NumericValue': 9.1531329,
  'Low': 4.7453247,
  'High': 15.400498,
  'Comments': None,
  'Date': '2024-11-13T10:26:48.993+01:00',
  'TimeDimensionValue': '1992',
  'TimeDimensionBegin': '1992-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1992-12-31T00:00:00+01:00'},
 {'Id': 6253,
  'IndicatorCode': 'NCD_DIABETES_PREVALENCE_AGESTD',
  'SpatialDimType': 'WORLDBANKINCOMEGROUP',
  'SpatialDim': 'WB_LMI',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2012,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-PLUS',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '18.8 [17.4-20.2]',
  'NumericValue': 18.784387,

In [25]:
thirdIndicatorDataDataFrame = pd.DataFrame(thirdIndicatorData)
thirdIndicatorDataDataFrame = thirdIndicatorDataDataFrame.loc[thirdIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
thirdIndicatorDataDataFrame = thirdIndicatorDataDataFrame[(thirdIndicatorDataDataFrame['Dim1'] == 'SEX_BTSX')]
thirdIndicatorDataDataFrame['Value'] = thirdIndicatorDataDataFrame['Value'].astype('string')
thirdIndicatorDataDataFrame['Value'] = thirdIndicatorDataDataFrame['Value'].str.split(' ').str[0]
thirdIndicatorDataDataFrame['Value'] = thirdIndicatorDataDataFrame['Value'].astype('float')
thirdIndicatorDataDataFrame = thirdIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Dim1','Dim2','Value']]
thirdIndicatorDataDataFrame

,Id,IndicatorCode,SpatialDim,TimeDim,Dim1,Dim2,Value
9,959,NCD_DIABETES_PREVALENCE_AGESTD,LTU,2002,SEX_BTSX,AGEGROUP_YEARS18-PLUS,7.2
23,5429,NCD_DIABETES_PREVALENCE_AGESTD,ROU,2002,SEX_BTSX,AGEGROUP_YEARS30-PLUS,5.1
28,6337,NCD_DIABETES_PREVALENCE_AGESTD,DNK,2001,SEX_BTSX,AGEGROUP_YEARS30-PLUS,4.0
36,8438,NCD_DIABETES_PREVALENCE_AGESTD,SVN,2002,SEX_BTSX,AGEGROUP_YEARS30-PLUS,8.3
56,14257,NCD_DIABETES_PREVALENCE_AGESTD,AUT,1991,SEX_BTSX,AGEGROUP_YEARS18-PLUS,3.7
...,...,...,...,...,...,...,...
41475,10181482,NCD_DIABETES_PREVALENCE_AGESTD,SVK,2019,SEX_BTSX,AGEGROUP_YEARS30-PLUS,10.7
41491,10185239,NCD_DIABETES_PREVALENCE_AGESTD,SVK,1995,SEX_BTSX,AGEGROUP_YEARS30-PLUS,7.2
41508,10189473,NCD_DIABETES_PREVALENCE_AGESTD,HUN,2006,SEX_BTSX,AGEGROUP_YEARS30-PLUS,10.1
41523,10193666,NCD_DIABETES_PREVALENCE_AGESTD,ITA,2022,SEX_BTSX,AGEGROUP_YEARS18-PLUS,7.2
41570,10204169,NCD_DIABETES_PREVALENCE_AGESTD,FIN,2021,SEX_BTSX,AGEGROUP_YEARS30-PLUS,9.4

In [27]:
thirdIndicatorDataDataFrame18Plus = thirdIndicatorDataDataFrame.loc[thirdIndicatorDataDataFrame['Dim2'] == 'AGEGROUP_YEARS18-PLUS']
thirdIndicatorDataDataFrame18Plus

,Id,IndicatorCode,SpatialDim,TimeDim,Dim1,Dim2,Value
9,959,NCD_DIABETES_PREVALENCE_AGESTD,LTU,2002,SEX_BTSX,AGEGROUP_YEARS18-PLUS,7.2
56,14257,NCD_DIABETES_PREVALENCE_AGESTD,AUT,1991,SEX_BTSX,AGEGROUP_YEARS18-PLUS,3.7
62,14911,NCD_DIABETES_PREVALENCE_AGESTD,SWE,2012,SEX_BTSX,AGEGROUP_YEARS18-PLUS,4.3
112,28962,NCD_DIABETES_PREVALENCE_AGESTD,DNK,2010,SEX_BTSX,AGEGROUP_YEARS18-PLUS,2.8
144,36743,NCD_DIABETES_PREVALENCE_AGESTD,FIN,2018,SEX_BTSX,AGEGROUP_YEARS18-PLUS,6.6
...,...,...,...,...,...,...,...
41160,10107730,NCD_DIABETES_PREVALENCE_AGESTD,DEU,2005,SEX_BTSX,AGEGROUP_YEARS18-PLUS,6.8
41226,10123830,NCD_DIABETES_PREVALENCE_AGESTD,GRC,1992,SEX_BTSX,AGEGROUP_YEARS18-PLUS,5.5
41405,10166506,NCD_DIABETES_PREVALENCE_AGESTD,SVK,1996,SEX_BTSX,AGEGROUP_YEARS18-PLUS,5.3
41414,10169143,NCD_DIABETES_PREVALENCE_AGESTD,BGR,2014,SEX_BTSX,AGEGROUP_YEARS18-PLUS,8.3
41523,10193666,NCD_DIABETES_PREVALENCE_AGESTD,ITA,2022,SEX_BTSX,AGEGROUP_YEARS18-PLUS,7.2

In [28]:
thirdIndicatorDataDataFrame30Plus = thirdIndicatorDataDataFrame.loc[thirdIndicatorDataDataFrame['Dim2'] == 'AGEGROUP_YEARS30-PLUS']
thirdIndicatorDataDataFrame30Plus

,Id,IndicatorCode,SpatialDim,TimeDim,Dim1,Dim2,Value
23,5429,NCD_DIABETES_PREVALENCE_AGESTD,ROU,2002,SEX_BTSX,AGEGROUP_YEARS30-PLUS,5.1
28,6337,NCD_DIABETES_PREVALENCE_AGESTD,DNK,2001,SEX_BTSX,AGEGROUP_YEARS30-PLUS,4.0
36,8438,NCD_DIABETES_PREVALENCE_AGESTD,SVN,2002,SEX_BTSX,AGEGROUP_YEARS30-PLUS,8.3
58,14317,NCD_DIABETES_PREVALENCE_AGESTD,DEU,1999,SEX_BTSX,AGEGROUP_YEARS30-PLUS,8.6
160,41599,NCD_DIABETES_PREVALENCE_AGESTD,EST,2003,SEX_BTSX,AGEGROUP_YEARS30-PLUS,6.6
...,...,...,...,...,...,...,...
41392,10164874,NCD_DIABETES_PREVALENCE_AGESTD,SWE,2017,SEX_BTSX,AGEGROUP_YEARS30-PLUS,6.0
41475,10181482,NCD_DIABETES_PREVALENCE_AGESTD,SVK,2019,SEX_BTSX,AGEGROUP_YEARS30-PLUS,10.7
41491,10185239,NCD_DIABETES_PREVALENCE_AGESTD,SVK,1995,SEX_BTSX,AGEGROUP_YEARS30-PLUS,7.2
41508,10189473,NCD_DIABETES_PREVALENCE_AGESTD,HUN,2006,SEX_BTSX,AGEGROUP_YEARS30-PLUS,10.1
41570,10204169,NCD_DIABETES_PREVALENCE_AGESTD,FIN,2021,SEX_BTSX,AGEGROUP_YEARS30-PLUS,9.4

In [34]:
mergedDf = pd.merge(thirdIndicatorDataDataFrame18Plus,thirdIndicatorDataDataFrame30Plus,on=['SpatialDim','TimeDim'])
mergedDf['meanValue'] = (mergedDf['Value_x'] + mergedDf['Value_y']) / 2
mergedDf['newDim2'] = 'AGEGROUP_ALLYEARS'
mergedDf = mergedDf[['Id_x','IndicatorCode_x','SpatialDim','TimeDim','Dim1_x','newDim2','meanValue']]
mergedDf

,Id_x,IndicatorCode_x,SpatialDim,TimeDim,Dim1_x,newDim2,meanValue
0,959,NCD_DIABETES_PREVALENCE_AGESTD,LTU,2002,SEX_BTSX,AGEGROUP_ALLYEARS,8.30
1,14257,NCD_DIABETES_PREVALENCE_AGESTD,AUT,1991,SEX_BTSX,AGEGROUP_ALLYEARS,4.35
2,14911,NCD_DIABETES_PREVALENCE_AGESTD,SWE,2012,SEX_BTSX,AGEGROUP_ALLYEARS,5.00
3,28962,NCD_DIABETES_PREVALENCE_AGESTD,DNK,2010,SEX_BTSX,AGEGROUP_ALLYEARS,3.25
4,36743,NCD_DIABETES_PREVALENCE_AGESTD,FIN,2018,SEX_BTSX,AGEGROUP_ALLYEARS,7.65
...,...,...,...,...,...,...,...
886,10107730,NCD_DIABETES_PREVALENCE_AGESTD,DEU,2005,SEX_BTSX,AGEGROUP_ALLYEARS,8.00
887,10123830,NCD_DIABETES_PREVALENCE_AGESTD,GRC,1992,SEX_BTSX,AGEGROUP_ALLYEARS,6.50
888,10166506,NCD_DIABETES_PREVALENCE_AGESTD,SVK,1996,SEX_BTSX,AGEGROUP_ALLYEARS,6.25
889,10169143,NCD_DIABETES_PREVALENCE_AGESTD,BGR,2014,SEX_BTSX,AGEGROUP_ALLYEARS,9.65
890,10193666,NCD_DIABETES_PREVALENCE_AGESTD,ITA,2022,SEX_BTSX,AGEGROUP_ALLYEARS,8.45

In [41]:
saveToParquet(mergedDf,'ncdDiabetes')

In [42]:
fourthIndicator = ncdIndicatorsDf.iloc[3]
fourthIndicator

IndicatorCode                                             WHS2_131
IndicatorName    Age-standardized NCD mortality rate  (per 100 ...
Language                                                        EN
Category                                            NCD: Mortality
Name: 3, dtype: object

In [44]:
fourthIndicatorData = getData(baseURL,fourthIndicator['IndicatorCode'])
fourthIndicatorData = fourthIndicatorData['value']
fourthIndicatorData

[{'Id': 2683,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MNG',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 2008,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1150 [800-1640]',
  'NumericValue': 1154.453613281,
  'Low': 795.569702148,
  'High': 1643.545288086,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 7584,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'VNM',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 2002,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '560 [380-920]',
  'NumericValue': 564.58203125,
  'Low': 378.87197876,
  'High': 915.850341797,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2002',
  'TimeDimensionBegin': '2002-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2002-12-31T00:00:00+01:00'},
 {'Id': 7761,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ITA',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2015,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '390 [330-450]',
  'NumericValue': 388.302093506,
  'Low': 329.329803467,
  'High': 449.941070557,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2015',
  'TimeDimensionBegin': '2015-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2015-12-31T00:00:00+01:00'},
 {'Id': 8306,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BOL',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2018,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '530 [240-720]',
  'NumericValue': 532.339111328,
  'Low': 240.799758911,
  'High': 719.994750977,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 9083,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'REGION',
  'SpatialDim': 'SEAR',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 2014,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '510 [370-720]',
  'NumericValue': 513.125549316,
  'Low': 367.817657471,
  'High': 723.472290039,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 13957,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SLE',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2007,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '690 [400-1140]',
  'NumericValue': 692.518249512,
  'Low': 396.741638184,
  'High': 1143.28112793,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 14504,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'REGION',
  'SpatialDim': 'EMR',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 2015,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '680 [440-980]',
  'NumericValue': 683.153686523,
  'Low': 441.366943359,
  'High': 979.37512207,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2015',
  'TimeDimensionBegin': '2015-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2015-12-31T00:00:00+01:00'},
 {'Id': 20867,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CAN',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2013,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '380 [300-460]',
  'NumericValue': 377.850463867,
  'Low': 302.091918945,
  'High': 464.15713501,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2013',
  'TimeDimensionBegin': '2013-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2013-12-31T00:00:00+01:00'},
 {'Id': 21289,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'REGION',
  'SpatialDim': 'AFR',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 2020,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '600 [340-950]',
  'NumericValue': 601.875,
  'Low': 340.742126465,
  'High': 946.835998535,
  'Comments': 'For this geography and year, some non-communicable disease deaths may be included in a separate category called "other pandemic-related mortality" due to lack of vital registration data. Estimates of this indicator for 2020 and 2021 may be underestimated, and should be interpreted with caution.',
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 27934,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SLB',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 2019,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '930 [500-1220]',
  'NumericValue': 934.530883789,
  'Low': 501.173828125,
  'High': 1223.597167969,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2019',
  'TimeDimensionBegin': '2019-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2019-12-31T00:00:00+01:00'},
 {'Id': 39682,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PSE',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2008,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '630 [440-870]',
  'NumericValue': 627.620910645,
  'Low': 443.543243408,
  'High': 866.592285156,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 45848,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PAK',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2008,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '730 [470-1080]',
  'NumericValue': 728.057434082,
  'Low': 467.44631958,
  'High': 1079.571044922,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 46094,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SSD',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2000,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '570 [290-1040]',
  'NumericValue': 567.75604248,
  'Low': 287.866790771,
  'High': 1043.255859375,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2000',
  'TimeDimensionBegin': '2000-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2000-12-31T00:00:00+01:00'},
 {'Id': 46828,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LTU',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2018,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '380 [310-480]',
  'NumericValue': 377.030578613,
  'Low': 312.749816895,
  'High': 483.873443604,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 52503,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TUR',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2006,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '480 [290-630]',
  'NumericValue': 482.273620605,
  'Low': 287.670715332,
  'High': 633.927734375,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2006',
  'TimeDimensionBegin': '2006-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2006-12-31T00:00:00+01:00'},
 {'Id': 65963,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ATG',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2005,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '470 [360-570]',
  'NumericValue': 468.353393555,
  'Low': 364.797668457,
  'High': 565.056030273,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 66172,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'NER',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2005,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '580 [280-1070]',
  'NumericValue': 580.184570313,
  'Low': 279.331665039,
  'High': 1074.318847656,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 66250,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ESP',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2000,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '310 [230-400]',
  'NumericValue': 305.598846436,
  'Low': 233.439224243,
  'High': 398.705596924,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2000',
  'TimeDimensionBegin': '2000-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2000-12-31T00:00:00+01:00'},
 {'Id': 71396,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CYP',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2005,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '400 [270-560]',
  'NumericValue': 396.005249023,
  'Low': 269.04989624,
  'High': 561.005554199,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 78518,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BOL',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2011,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '550 [260-790]',
  'NumericValue': 553.176025391,
  'Low': 262.265899658,
  'High': 794.536254883,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2011',
  'TimeDimensionBegin': '2011-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2011-12-31T00:00:00+01:00'},
 {'Id': 78850,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'COL',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2003,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '500 [390-600]',
  'NumericValue': 496.224853516,
  'Low': 390.152893066,
  'High': 595.25970459,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 84616,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TUN',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2012,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '390 [240-730]',
  'NumericValue': 394.424957275,
  'Low': 240.653198242,
  'High': 726.195983887,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 90803,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'QAT',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2021,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '460 [260-680]',
  'NumericValue': 459.001861572,
  'Low': 256.84286499,
  'High': 684.487915039,
  'Comments': 'For this geography and year, some non-communicable disease deaths may be included in a separate category called "other pandemic-related mortality" due to lack of vital registration data. Estimates of this indicator for 2020 and 2021 may be underestimated, and should be interpreted with caution.',
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2021',
  'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
 {'Id': 97854,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PAK',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2018,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '690 [430-1050]',
  'NumericValue': 691.51159668,
  'Low': 430.563262939,
  'High': 1050.403198242,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 102794,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PRK',
  'ParentLocationCode': 'SEAR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'South-East Asia',
  'Dim1Type': 'SEX',
  'TimeDim': 2006,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '560 [350-1000]',
  'NumericValue': 564.063171387,
  'Low': 349.328979492,
  'High': 998.272094727,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2006',
  'TimeDimensionBegin': '2006-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2006-12-31T00:00:00+01:00'},
 {'Id': 102826,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TUN',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2005,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '520 [350-920]',
  'NumericValue': 519.454345703,
  'Low': 351.488861084,
  'High': 920.727783203,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 103147,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BLR',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2007,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '570 [500-720]',
  'NumericValue': 574.833312988,
  'Low': 503.348449707,
  'High': 715.412109375,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 103205,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ISL',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2016,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '350 [280-440]',
  'NumericValue': 350.970397949,
  'Low': 277.90838623,
  'High': 444.030700684,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 103372,
  'IndicatorCode': 'WHS2_131',
  'SpatialDimType': 'REGION',
  'SpatialDim': 'SEAR',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',

In [45]:
fourthIndicatorDataDataFrame = pd.DataFrame(fourthIndicatorData)
fourthIndicatorDataDataFrame = fourthIndicatorDataDataFrame.loc[fourthIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
fourthIndicatorDataDataFrame = fourthIndicatorDataDataFrame.loc[fourthIndicatorDataDataFrame['Dim1'] == 'SEX_BTSX']
fourthIndicatorDataDataFrame['Value'] = fourthIndicatorDataDataFrame['Value'].astype('string')
fourthIndicatorDataDataFrame['Value'] = fourthIndicatorDataDataFrame['Value'].str.split(' ').str[0]
fourthIndicatorDataDataFrame['Value'] = fourthIndicatorDataDataFrame['Value'].astype('float')
fourthIndicatorDataDataFrame = fourthIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Dim1','Value']]
fourthIndicatorDataDataFrame

             Id IndicatorCode SpatialDim  TimeDim      Dim1  Value
18        71396      WHS2_131        CYP     2005  SEX_BTSX  400.0
48       178584      WHS2_131        SVK     2011  SEX_BTSX  550.0
65       242153      WHS2_131        ROU     2002  SEX_BTSX  770.0
96       356867      WHS2_131        BGR     2020  SEX_BTSX  650.0
106      382764      WHS2_131        CZE     2010  SEX_BTSX  480.0
...         ...           ...        ...      ...       ...    ...
12766   9636213      WHS2_131        CYP     2019  SEX_BTSX  310.0
12828   9812964      WHS2_131        PRT     2007  SEX_BTSX  400.0
12833   9831630      WHS2_131        DNK     2003  SEX_BTSX  490.0
12906  10122397      WHS2_131        HUN     2008  SEX_BTSX  650.0
12916  10154014      WHS2_131        ITA     2003  SEX_BTSX  400.0

[594 rows x 6 columns]

In [48]:
saveToParquet(fourthIndicatorDataDataFrame,'ncdMortalityRatePer100000')

In [47]:
fifthIndicator = ncdIndicatorsDf.iloc[4]
fifthIndicator

IndicatorCode         NCD_DTH_TOT
IndicatorName    Total NCD Deaths
Language                       EN
Category           NCD: Mortality
Name: 4, dtype: object

In [49]:
fifthIndicatorData = getData(baseURL,fifthIndicator['IndicatorCode'])
fifthIndicatorData = fifthIndicatorData['value']
fifthIndicatorData

[{'Id': 9454999,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ISL',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2015,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '980 [700-1320]',
  'NumericValue': 975.0,
  'Low': 703.0,
  'High': 1319.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2015',
  'TimeDimensionBegin': '2015-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2015-12-31T00:00:00+01:00'},
 {'Id': 9455488,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'POL',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2014,
  'Dim1': 'SEX_MLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '170 000 [158 000-189 000]',
  'NumericValue': 169907.0,
  'Low': 157504.0,
  'High': 189352.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 9455854,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'REGION',
  'SpatialDim': 'AFR',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 2003,
  'Dim1': 'SEX_MLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1 010 000 [576 000-1 620 000]',
  'NumericValue': 1012147.0,
  'Low': 576048.0,
  'High': 1618331.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 932,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PRY',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2011,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '8320 [5670-12 500]',
  'NumericValue': 8320.0,
  'Low': 5670.0,
  'High': 12451.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2011',
  'TimeDimensionBegin': '2011-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2011-12-31T00:00:00+01:00'},
 {'Id': 1096,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SOM',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2004,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '16 600 [7190-31 800]',
  'NumericValue': 16566.0,
  'Low': 7193.0,
  'High': 31786.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2004',
  'TimeDimensionBegin': '2004-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2004-12-31T00:00:00+01:00'},
 {'Id': 1189,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SVK',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2006,
  'Dim1': 'SEX_MLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '24 200 [18 900-30 500]',
  'NumericValue': 24198.0,
  'Low': 18850.0,
  'High': 30524.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2006',
  'TimeDimensionBegin': '2006-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2006-12-31T00:00:00+01:00'},
 {'Id': 1614,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CZE',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2021,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '50 600 [38 600-65 000]',
  'NumericValue': 50584.0,
  'Low': 38629.0,
  'High': 64951.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2021',
  'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
 {'Id': 1952,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SAU',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2011,
  'Dim1': 'SEX_MLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '28 000 [18 400-40 900]',
  'NumericValue': 27964.0,
  'Low': 18410.0,
  'High': 40914.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2011',
  'TimeDimensionBegin': '2011-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2011-12-31T00:00:00+01:00'},
 {'Id': 3325,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PRT',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2005,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '46 600 [36 600-62 200]',
  'NumericValue': 46561.0,
  'Low': 36641.0,
  'High': 62221.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 3343,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TKM',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2020,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '28 600 [20 700-38 700]',
  'NumericValue': 28600.0,
  'Low': 20685.0,
  'High': 38707.0,
  'Comments': 'For this geography and year, some non-communicable disease deaths may be included in a separate category called "other pandemic-related mortality" due to lack of vital registration data. Estimates of this indicator for 2020 and 2021 may be underestimated, and should be interpreted with caution.',
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 4805,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BGD',
  'ParentLocationCode': 'SEAR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'South-East Asia',
  'Dim1Type': 'SEX',
  'TimeDim': 2009,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '196 000 [122 000-329 000]',
  'NumericValue': 195672.0,
  'Low': 121904.0,
  'High': 328694.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2009',
  'TimeDimensionBegin': '2009-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2009-12-31T00:00:00+01:00'},
 {'Id': 4875,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DJI',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2004,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '2510 [1250-4510]',
  'NumericValue': 2505.0,
  'Low': 1246.0,
  'High': 4507.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2004',
  'TimeDimensionBegin': '2004-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2004-12-31T00:00:00+01:00'},
 {'Id': 8074,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'YEM',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2012,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '72 700 [36 200-114 000]',
  'NumericValue': 72729.0,
  'Low': 36217.0,
  'High': 114120.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 8934,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KIR',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 2006,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '560 [320-880]',
  'NumericValue': 563.0,
  'Low': 318.0,
  'High': 885.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2006',
  'TimeDimensionBegin': '2006-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2006-12-31T00:00:00+01:00'},
 {'Id': 9692,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'VCT',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2010,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '310 [260-380]',
  'NumericValue': 307.0,
  'Low': 256.0,
  'High': 381.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 9767,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MMR',
  'ParentLocationCode': 'SEAR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'South-East Asia',
  'Dim1Type': 'SEX',
  'TimeDim': 2009,
  'Dim1': 'SEX_MLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '127 000 [76 900-195 000]',
  'NumericValue': 127186.0,
  'Low': 76869.0,
  'High': 194632.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2009',
  'TimeDimensionBegin': '2009-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2009-12-31T00:00:00+01:00'},
 {'Id': 9881,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GEO',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2012,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '24 100 [18 600-27 400]',
  'NumericValue': 24100.0,
  'Low': 18606.0,
  'High': 27419.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 11222,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'OMN',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2018,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '3690 [2220-5360]',
  'NumericValue': 3686.0,
  'Low': 2223.0,
  'High': 5359.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 11660,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TKM',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2011,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '22 300 [18 100-27 000]',
  'NumericValue': 22320.0,
  'Low': 18058.0,
  'High': 27026.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2011',
  'TimeDimensionBegin': '2011-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2011-12-31T00:00:00+01:00'},
 {'Id': 11862,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GBR',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2009,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '495 000 [416 000-574 000]',
  'NumericValue': 494862.0,
  'Low': 416176.0,
  'High': 573635.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2009',
  'TimeDimensionBegin': '2009-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2009-12-31T00:00:00+01:00'},
 {'Id': 12202,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'FRA',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2005,
  'Dim1': 'SEX_MLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '233 000 [189 000-282 000]',
  'NumericValue': 232884.0,
  'Low': 188644.0,
  'High': 282332.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 14458,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GIN',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2003,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '29 200 [15 600-48 900]',
  'NumericValue': 29212.0,
  'Low': 15576.0,
  'High': 48876.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 14657,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LKA',
  'ParentLocationCode': 'SEAR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'South-East Asia',
  'Dim1Type': 'SEX',
  'TimeDim': 2017,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '115 000 [72 100-166 000]',
  'NumericValue': 114544.0,
  'Low': 72121.0,
  'High': 165757.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2017',
  'TimeDimensionBegin': '2017-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2017-12-31T00:00:00+01:00'},
 {'Id': 15621,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'RWA',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2017,
  'Dim1': 'SEX_MLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '16 600 [8230-30 700]',
  'NumericValue': 16635.0,
  'Low': 8231.0,
  'High': 30737.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2017',
  'TimeDimensionBegin': '2017-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2017-12-31T00:00:00+01:00'},
 {'Id': 16450,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'IRQ',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2018,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '50 700 [33 000-78 400]',
  'NumericValue': 50690.0,
  'Low': 33023.0,
  'High': 78421.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 16842,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ETH',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2021,
  'Dim1': 'SEX_MLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '125 000 [74 700-202 000]',
  'NumericValue': 125431.0,
  'Low': 74715.0,
  'High': 202312.0,
  'Comments': 'For this geography and year, some non-communicable disease deaths may be included in a separate category called "other pandemic-related mortality" due to lack of vital registration data. Estimates of this indicator for 2020 and 2021 may be underestimated, and should be interpreted with caution.',
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2021',
  'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
 {'Id': 18330,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GNB',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2007,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4910 [2520-8400]',
  'NumericValue': 4911.0,
  'Low': 2516.0,
  'High': 8401.0,
  'Comments': None,
  'Date': '2025-03-19T11:00:50.48+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 19639,
  'IndicatorCode': 'NCD_DTH_TOT',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KWT',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2008,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'GHECAUSES',
  'Dim2': 'GHECAUSES_GHE060',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1350 [1040-1710]',
  'NumericValue': 1352.0,
  'Low': 1040.0,

In [55]:
fifthIndicatorDataDataFrame = pd.DataFrame(fifthIndicatorData)
fifthIndicatorDataDataFrame = fifthIndicatorDataDataFrame.loc[fifthIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
fifthIndicatorDataDataFrame = fifthIndicatorDataDataFrame.loc[fifthIndicatorDataDataFrame['Dim1'] == 'SEX_BTSX']
fifthIndicatorDataDataFrame['Value'] = fifthIndicatorDataDataFrame['Value'].astype('string')
fifthIndicatorDataDataFrame['Value'] = fifthIndicatorDataDataFrame['Value'].str.split(' ').str[0]
fifthIndicatorDataDataFrame['Value'] = fifthIndicatorDataDataFrame['Value'].astype('float')
fifthIndicatorDataDataFrame = fifthIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Dim1','Value']]
fifthIndicatorDataDataFrame

             Id IndicatorCode SpatialDim  TimeDim      Dim1   Value
37        27058   NCD_DTH_TOT        FRA     2001  SEX_BTSX   459.0
40        29167   NCD_DTH_TOT        HRV     2018  SEX_BTSX    47.0
42        29635   NCD_DTH_TOT        LVA     2008  SEX_BTSX    28.0
44        34390   NCD_DTH_TOT        CYP     2002  SEX_BTSX  5310.0
63        49028   NCD_DTH_TOT        SVK     2009  SEX_BTSX    47.0
...         ...           ...        ...      ...       ...     ...
12748  10066946   NCD_DTH_TOT        HRV     2010  SEX_BTSX    47.0
12827  10121434   NCD_DTH_TOT        SVN     2012  SEX_BTSX    16.0
12834  10125647   NCD_DTH_TOT        MLT     2001  SEX_BTSX  2700.0
12872  10154288   NCD_DTH_TOT        ROU     2015  SEX_BTSX   239.0
12894  10175333   NCD_DTH_TOT        CYP     2015  SEX_BTSX  6370.0

[594 rows x 6 columns]

In [56]:
saveToParquet(fifthIndicatorDataDataFrame,'totalNCDdeaths')

In [57]:
sixthIndicator = ncdIndicatorsDf.iloc[5]
sixthIndicator

IndicatorCode                                          NCDMORT3070
IndicatorName    Probability (%) of dying between age 30 and ex...
Language                                                        EN
Category                                            NCD: Mortality
Name: 5, dtype: object

In [58]:
sixthIndicator['IndicatorName']

'Probability (%) of dying between age 30 and exact age 70 from any of cardiovascular disease, cancer, diabetes, or chronic respiratory disease'

In [59]:
sixthIndicatorData = getData(baseURL,sixthIndicator['IndicatorCode'])
sixthIndicatorData = sixthIndicatorData['value']
sixthIndicatorData

[{'Id': 4213,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AGO',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2000,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '27.8 [16.1-40.1]',
  'NumericValue': 27.8,
  'Low': 16.1,
  'High': 40.1,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2000',
  'TimeDimensionBegin': '2000-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2000-12-31T00:00:00+01:00'},
 {'Id': 8902,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ZWE',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2021,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '31.2 [19.2-42.9]',
  'NumericValue': 31.2,
  'Low': 19.2,
  'High': 42.9,
  'Comments': 'For this geography and year, some non-communicable disease deaths may be included in a separate category called "other pandemic-related mortality" due to lack of vital registration data. Estimates of this indicator for 2020 and 2021 may be underestimated, and need to be interpreted with caution.',
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2021',
  'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
 {'Id': 8906,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GMB',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2006,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '26.2 [16.5-37.7]',
  'NumericValue': 26.2,
  'Low': 16.5,
  'High': 37.7,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2006',
  'TimeDimensionBegin': '2006-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2006-12-31T00:00:00+01:00'},
 {'Id': 8953,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BRA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2020,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '14.7 [13.7-15.8]',
  'NumericValue': 14.7,
  'Low': 13.7,
  'High': 15.8,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 10610,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AFG',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2003,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '42.5 [25.6-60.1]',
  'NumericValue': 42.5,
  'Low': 25.6,
  'High': 60.1,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 10619,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MUS',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2013,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '28.6 [24.9-32.8]',
  'NumericValue': 28.6,
  'Low': 24.9,
  'High': 32.8,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2013',
  'TimeDimensionBegin': '2013-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2013-12-31T00:00:00+01:00'},
 {'Id': 10821,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KWT',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2020,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '11.0 [9.3-12.9]',
  'NumericValue': 11.0,
  'Low': 9.3,
  'High': 12.9,
  'Comments': 'For this geography and year, some non-communicable disease deaths may be included in a separate category called "other pandemic-related mortality" due to lack of vital registration data. Estimates of this indicator for 2020 and 2021 may be underestimated, and need to be interpreted with caution.',
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 14857,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'REGION',
  'SpatialDim': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': None,
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2008,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '27.1 [24.7-29.5]',
  'NumericValue': 27.1,
  'Low': 24.7,
  'High': 29.5,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 15442,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TZA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2004,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '18.6 [12.0-28.1]',
  'NumericValue': 18.6,
  'Low': 12.0,
  'High': 28.1,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2004',
  'TimeDimensionBegin': '2004-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2004-12-31T00:00:00+01:00'},
 {'Id': 15456,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SEN',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2005,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '22.4 [13.9-31.3]',
  'NumericValue': 22.4,
  'Low': 13.9,
  'High': 31.3,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 16065,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SWE',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2007,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '9.2 [8.1-10.4]',
  'NumericValue': 9.2,
  'Low': 8.1,
  'High': 10.4,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 16420,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AFG',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2003,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '45.3 [29.0-62.7]',
  'NumericValue': 45.3,
  'Low': 29.0,
  'High': 62.7,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 16610,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TKM',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2007,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '43.1 [40.6-49.7]',
  'NumericValue': 43.1,
  'Low': 40.6,
  'High': 49.7,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 16620,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MDA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2005,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '35.6 [32.4-39.5]',
  'NumericValue': 35.6,
  'Low': 32.4,
  'High': 39.5,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 22314,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BRA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2007,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '18.1 [17.5-19.7]',
  'NumericValue': 18.1,
  'Low': 17.5,
  'High': 19.7,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 26689,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BIH',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2011,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '14.5 [10.5-17.9]',
  'NumericValue': 14.5,
  'Low': 10.5,
  'High': 17.9,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2011',
  'TimeDimensionBegin': '2011-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2011-12-31T00:00:00+01:00'},
 {'Id': 33807,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TZA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2012,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '17.1 [11.2-26.9]',
  'NumericValue': 17.1,
  'Low': 11.2,
  'High': 26.9,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 33877,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'EGY',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2020,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '30.6 [21.7-37.6]',
  'NumericValue': 30.6,
  'Low': 21.7,
  'High': 37.6,
  'Comments': 'For this geography and year, some non-communicable disease deaths may be included in a separate category called "other pandemic-related mortality" due to lack of vital registration data. Estimates of this indicator for 2020 and 2021 may be underestimated, and need to be interpreted with caution.',
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 34090,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ARG',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2006,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '17.8 [15.2-20.3]',
  'NumericValue': 17.8,
  'Low': 15.2,
  'High': 20.3,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2006',
  'TimeDimensionBegin': '2006-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2006-12-31T00:00:00+01:00'},
 {'Id': 35946,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CIV',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2002,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '26.2 [17.4-38.3]',
  'NumericValue': 26.2,
  'Low': 17.4,
  'High': 38.3,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2002',
  'TimeDimensionBegin': '2002-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2002-12-31T00:00:00+01:00'},
 {'Id': 36216,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BRN',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2001,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '17.4 [12.7-23.8]',
  'NumericValue': 17.4,
  'Low': 12.7,
  'High': 23.8,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2001',
  'TimeDimensionBegin': '2001-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2001-12-31T00:00:00+01:00'},
 {'Id': 36414,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SSD',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2016,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '16.0 [8.9-26.1]',
  'NumericValue': 16.0,
  'Low': 8.9,
  'High': 26.1,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 39993,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BLZ',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2014,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '15.4 [13.2-18.5]',
  'NumericValue': 15.4,
  'Low': 13.2,
  'High': 18.5,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 40889,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ITA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2021,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '7.1 [6.4-7.7]',
  'NumericValue': 7.1,
  'Low': 6.4,
  'High': 7.7,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2021',
  'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
 {'Id': 41265,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'UZB',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2007,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '48.0 [40.9-52.9]',
  'NumericValue': 48.0,
  'Low': 40.9,
  'High': 52.9,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 42493,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'WORLDBANKINCOMEGROUP',
  'SpatialDim': 'WB_HI',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': None,
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2004,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '23.2 [21.6-24.7]',
  'NumericValue': 23.2,
  'Low': 21.6,
  'High': 24.7,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2004',
  'TimeDimensionBegin': '2004-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2004-12-31T00:00:00+01:00'},
 {'Id': 46103,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'OMN',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2019,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '20.3 [14.4-28.8]',
  'NumericValue': 20.3,
  'Low': 14.4,
  'High': 28.8,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',
  'TimeDimensionValue': '2019',
  'TimeDimensionBegin': '2019-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2019-12-31T00:00:00+01:00'},
 {'Id': 47004,
  'IndicatorCode': 'NCDMORT3070',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ETH',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2014,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS30-69',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '16.8 [11.7-23.0]',
  'NumericValue': 16.8,
  'Low': 11.7,
  'High': 23.0,
  'Comments': None,
  'Date': '2024-12-18T14:54:42.07+01:00',

In [60]:
sixthIndicatorDataDataFrame = pd.DataFrame(sixthIndicatorData)
sixthIndicatorDataDataFrame

,Id,IndicatorCode,SpatialDimType,SpatialDim,TimeDimType,ParentLocationCode,ParentLocation,Dim1Type,Dim1,TimeDim,...,DataSourceDim,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,4213,NCDMORT3070,COUNTRY,AGO,YEAR,AFR,Africa,SEX,SEX_FMLE,2000,...,None,27.8 [16.1-40.1],27.8,16.1,40.1,None,2024-12-18T14:54:42.07+01:00,2000,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00
1,8902,NCDMORT3070,COUNTRY,ZWE,YEAR,AFR,Africa,SEX,SEX_BTSX,2021,...,None,31.2 [19.2-42.9],31.2,19.2,42.9,"For this geography and year, some non-communic...",2024-12-18T14:54:42.07+01:00,2021,2021-01-01T00:00:00+01:00,2021-12-31T00:00:00+01:00
2,8906,NCDMORT3070,COUNTRY,GMB,YEAR,AFR,Africa,SEX,SEX_MLE,2006,...,None,26.2 [16.5-37.7],26.2,16.5,37.7,None,2024-12-18T14:54:42.07+01:00,2006,2006-01-01T00:00:00+01:00,2006-12-31T00:00:00+01:00
3,8953,NCDMORT3070,COUNTRY,BRA,YEAR,AMR,Americas,SEX,SEX_BTSX,2020,...,None,14.7 [13.7-15.8],14.7,13.7,15.8,None,2024-12-18T14:54:42.07+01:00,2020,2020-01-01T00:00:00+01:00,2020-12-31T00:00:00+01:00
4,10610,NCDMORT3070,COUNTRY,AFG,YEAR,EMR,Eastern Mediterranean,SEX,SEX_BTSX,2003,...,None,42.5 [25.6-60.1],42.5,25.6,60.1,None,2024-12-18T14:54:42.07+01:00,2003,2003-01-01T00:00:00+01:00,2003-12-31T00:00:00+01:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12931,10198987,NCDMORT3070,COUNTRY,SSD,YEAR,AFR,Africa,SEX,SEX_MLE,2000,...,None,23.7 [14.3-37.0],23.7,14.3,37.0,None,2024-12-18T14:54:42.07+01:00,2000,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00
12932,10203921,NCDMORT3070,COUNTRY,ISL,YEAR,EUR,Europe,SEX,SEX_BTSX,2015,...,None,9.2 [7.6-10.9],9.2,7.6,10.9,None,2024-12-18T14:54:42.07+01:00,2015,2015-01-01T00:00:00+01:00,2015-12-31T00:00:00+01:00
12933,10203922,NCDMORT3070,COUNTRY,HUN,YEAR,EUR,Europe,SEX,SEX_BTSX,2021,...,None,21.7 [18.3-25.2],21.7,18.3,25.2,None,2024-12-18T14:54:42.07+01:00,2021,2021-01-01T00:00:00+01:00,2021-12-31T00:00:00+01:00
12934,10204218,NCDMORT3070,COUNTRY,LBN,YEAR,EMR,Eastern Mediterranean,SEX,SEX_FMLE,2020,...,None,9.6 [6.4-13.6],9.6,6.4,13.6,"For this geography and year, some non-communic...",2024-12-18T14:54:42.07+01:00,2020,2020-01-01T00:00:00+01:00,2020-12-31T00:00:00+01:00
12935,10205042,NCDMORT3070,COUNTRY,BGR,YEAR,EUR,Europe,SEX,SEX_MLE,2013,...,None,32.5 [29.1-36.3],32.5,29.1,36.3,None,2024-12-18T14:54:42.07+01:00,2013,2013-01-01T00:00:00+01:00,2013-12-31T00:00:00+01:00

In [63]:
sixthIndicatorDataDataFrame = pd.DataFrame(sixthIndicatorData)
sixthIndicatorDataDataFrame = sixthIndicatorDataDataFrame.loc[sixthIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
sixthIndicatorDataDataFrame = sixthIndicatorDataDataFrame.loc[sixthIndicatorDataDataFrame['Dim1'] == 'SEX_BTSX']
sixthIndicatorDataDataFrame['Value'] = sixthIndicatorDataDataFrame['Value'].astype('string')
sixthIndicatorDataDataFrame['Value'] = sixthIndicatorDataDataFrame['Value'].str.split(' ').str[0]
sixthIndicatorDataDataFrame['Value'] = sixthIndicatorDataDataFrame['Value'].astype('float')
sixthIndicatorDataDataFrame

,Id,IndicatorCode,SpatialDimType,SpatialDim,TimeDimType,ParentLocationCode,ParentLocation,Dim1Type,Dim1,TimeDim,...,DataSourceDim,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
29,47715,NCDMORT3070,COUNTRY,AUT,YEAR,EUR,Europe,SEX,SEX_BTSX,2018,...,None,10.9,10.9,9.3,12.7,None,2024-12-18T14:54:42.07+01:00,2018,2018-01-01T00:00:00+01:00,2018-12-31T00:00:00+01:00
80,122203,NCDMORT3070,COUNTRY,LTU,YEAR,EUR,Europe,SEX,SEX_BTSX,2020,...,None,20.7,20.7,17.8,24.2,None,2024-12-18T14:54:42.07+01:00,2020,2020-01-01T00:00:00+01:00,2020-12-31T00:00:00+01:00
118,179831,NCDMORT3070,COUNTRY,CYP,YEAR,EUR,Europe,SEX,SEX_BTSX,2008,...,None,11.0,11.0,8.3,14.4,None,2024-12-18T14:54:42.07+01:00,2008,2008-01-01T00:00:00+01:00,2008-12-31T00:00:00+01:00
123,192234,NCDMORT3070,COUNTRY,HUN,YEAR,EUR,Europe,SEX,SEX_BTSX,2004,...,None,26.8,26.8,23.8,29.9,None,2024-12-18T14:54:42.07+01:00,2004,2004-01-01T00:00:00+01:00,2004-12-31T00:00:00+01:00
160,242748,NCDMORT3070,COUNTRY,PRT,YEAR,EUR,Europe,SEX,SEX_BTSX,2015,...,None,11.5,11.5,9.7,13.4,None,2024-12-18T14:54:42.07+01:00,2015,2015-01-01T00:00:00+01:00,2015-12-31T00:00:00+01:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12871,10108158,NCDMORT3070,COUNTRY,POL,YEAR,EUR,Europe,SEX,SEX_BTSX,2011,...,None,20.0,20.0,19.5,21.2,None,2024-12-18T14:54:42.07+01:00,2011,2011-01-01T00:00:00+01:00,2011-12-31T00:00:00+01:00
12873,10108861,NCDMORT3070,COUNTRY,PRT,YEAR,EUR,Europe,SEX,SEX_BTSX,2014,...,None,11.5,11.5,9.7,13.4,None,2024-12-18T14:54:42.07+01:00,2014,2014-01-01T00:00:00+01:00,2014-12-31T00:00:00+01:00
12876,10114556,NCDMORT3070,COUNTRY,DEU,YEAR,EUR,Europe,SEX,SEX_BTSX,2018,...,None,12.1,12.1,10.4,14.0,None,2024-12-18T14:54:42.07+01:00,2018,2018-01-01T00:00:00+01:00,2018-12-31T00:00:00+01:00
12922,10190211,NCDMORT3070,COUNTRY,LTU,YEAR,EUR,Europe,SEX,SEX_BTSX,2015,...,None,22.2,22.2,19.9,25.7,None,2024-12-18T14:54:42.07+01:00,2015,2015-01-01T00:00:00+01:00,2015-12-31T00:00:00+01:00
12933,10203922,NCDMORT3070,COUNTRY,HUN,YEAR,EUR,Europe,SEX,SEX_BTSX,2021,...,None,21.7,21.7,18.3,25.2,None,2024-12-18T14:54:42.07+01:00,2021,2021-01-01T00:00:00+01:00,2021-12-31T00:00:00+01:00

In [ ]:
saveToParquet(sixthIndicatorDataDataFrame,'probabilityOfDying30-70NCD')