In [2]:
import pandas as pd 
import requests
from jsonschema import validate
import json
import fastparquet

In [4]:
pd.set_option('display.width', None)

In [3]:
countriesDf = pd.DataFrame(pd.read_parquet('../dataRawBeforeBlob/countries/euCountriesRaw.parquet'))
countriesDf

,Code,Title,ParentDimension,Dimension,ParentCode,ParentTitle
0,AUT,Austria,REGION,COUNTRY,EUR,Europe
1,BEL,Belgium,REGION,COUNTRY,EUR,Europe
2,BGR,Bulgaria,REGION,COUNTRY,EUR,Europe
3,CYP,Cyprus,REGION,COUNTRY,EUR,Europe
4,CZE,Czechia,REGION,COUNTRY,EUR,Europe
5,DEU,Germany,REGION,COUNTRY,EUR,Europe
6,DNK,Denmark,REGION,COUNTRY,EUR,Europe
7,ESP,Spain,REGION,COUNTRY,EUR,Europe
8,EST,Estonia,REGION,COUNTRY,EUR,Europe
9,FIN,Finland,REGION,COUNTRY,EUR,Europe
10,FRA,France,REGION,COUNTRY,EUR,Europe
11,GRC,Greece,REGION,COUNTRY,EUR,Europe
12,HRV,Croatia,REGION,COUNTRY,EUR,Europe
13,HUN,Hungary,REGION,COUNTRY,EUR,Europe
14,IRL,Ireland,REGION,COUNTRY,EUR,Europe
15,ITA,Italy,REGION,COUNTRY,EUR,Europe
16,LTU,Lithuania,REGION,COUNTRY,EUR,Europe
17,LUX,Luxembourg,REGION,COUNTRY,EUR,Europe
18,LVA,Latvia,REGION,COUNTRY,EUR,Europe
19,MLT,Malta,REGION,COUNTRY,EUR,Europe
20,NLD,Netherlands (Kingdom of the),REGION,COUNTRY,EUR,Europe
21,POL,Poland,REGION,COUNTRY,EUR,Europe
22,PRT,Portugal,REGION,COUNTRY,EUR,Europe
23,ROU,Romania,REGION,COUNTRY,EUR,Europe
24,SVK,Slovakia,REGION,COUNTRY,EUR,Europe
25,SVN,Slovenia,REGION,COUNTRY,EUR,Europe
26,SWE,Sweden,REGION,COUNTRY,EUR,Europe

In [5]:
baseURL= 'https://ghoapi.azureedge.net/api/'

In [9]:
lifeExpectancyIndicatorsDf = pd.DataFrame(pd.read_parquet('../dataRawBeforeBlob/indicators/lifeexpectancyIndicators.parquet',engine='fastparquet'))
lifeExpectancyIndicatorsDf

,IndicatorCode,IndicatorName,Language,Category
0,WHOSIS_000004,Adult mortality rate (probability of dying bet...,EN,Mortality and global health estimates
1,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),EN,Mortality and global health estimates
2,WHOSIS_000001,Life expectancy at birth (years),EN,Mortality and global health estimates
3,MDG_0000000007,Under-five mortality rate (probability of dyin...,EN,Child mortality and causes of death
4,WHOSIS_000003,Neonatal mortality rate (per 1000 live births),EN,Child mortality and causes of death
5,MORTADO,Adolescent mortality rate (per 1 000 age speci...,EN,Child mortality and causes of death

In [10]:
def getData(baseurl,indicatorCode:str):
    indicatorCode = indicatorCode.strip()
    response = requests.get(baseurl+f"{indicatorCode}")
    if response.status_code == 200 and response.headers.get('Content-Type').startswith('application/json') :
        return response.json()
    else:
        return 'Something went wrong with request'

In [11]:
def saveToParquet(df: pd.DataFrame,filename:str):
    df.to_parquet(f'../dataRawBeforeBlob/lifeExpectancyData/{filename}.parquet',engine='fastparquet')

In [12]:
firstIndicator = lifeExpectancyIndicatorsDf.iloc[0]
firstIndicator

IndicatorCode                                        WHOSIS_000004
IndicatorName    Adult mortality rate (probability of dying bet...
Language                                                        EN
Category                     Mortality and global health estimates
Name: 0, dtype: object

In [18]:
firstIndicatorData = getData(baseURL,firstIndicator['IndicatorCode'])
firstIndicatorData = firstIndicatorData['value']
firstIndicatorData

[{'Id': 3406,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'GLOBAL',
  'SpatialDim': 'GLOBAL',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2004,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '176',
  'NumericValue': 175.9135015,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2004',
  'TimeDimensionBegin': '2004-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2004-12-31T00:00:00+01:00'},
 {'Id': 3492,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'WSM',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2014,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '171',
  'NumericValue': 170.8641941,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 3655,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LAO',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2015,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '157',
  'NumericValue': 157.022125,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2015',
  'TimeDimensionBegin': '2015-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2015-12-31T00:00:00+01:00'},
 {'Id': 7736,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'HND',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2010,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '159',
  'NumericValue': 159.0012491,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 8134,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CRI',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2016,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '86',
  'NumericValue': 85.60958543,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 8212,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'REGION',
  'SpatialDim': 'AMR',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2011,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '85',
  'NumericValue': 84.92491091,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2011',
  'TimeDimensionBegin': '2011-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2011-12-31T00:00:00+01:00'},
 {'Id': 10620,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CAN',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2009,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '88',
  'NumericValue': 87.67882871,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2009',
  'TimeDimensionBegin': '2009-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2009-12-31T00:00:00+01:00'},
 {'Id': 11182,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'RWA',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2006,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '293',
  'NumericValue': 293.2279314,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2006',
  'TimeDimensionBegin': '2006-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2006-12-31T00:00:00+01:00'},
 {'Id': 14916,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'EST',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2001,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '224',
  'NumericValue': 224.0250448,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2001',
  'TimeDimensionBegin': '2001-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2001-12-31T00:00:00+01:00'},
 {'Id': 16254,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SWE',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2020,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '49',
  'NumericValue': 49.13531124,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 17254,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BWA',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2000,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '612',
  'NumericValue': 612.3394502,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2000',
  'TimeDimensionBegin': '2000-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2000-12-31T00:00:00+01:00'},
 {'Id': 20480,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MDA',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2001,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '249',
  'NumericValue': 248.8954829,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2001',
  'TimeDimensionBegin': '2001-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2001-12-31T00:00:00+01:00'},
 {'Id': 20828,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BOL',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2013,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '145',
  'NumericValue': 145.1400527,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2013',
  'TimeDimensionBegin': '2013-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2013-12-31T00:00:00+01:00'},
 {'Id': 21662,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PRI',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2010,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '110',
  'NumericValue': 110.33381,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 22007,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KWT',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2000,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '114',
  'NumericValue': 114.1883879,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2000',
  'TimeDimensionBegin': '2000-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2000-12-31T00:00:00+01:00'},
 {'Id': 22274,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'COL',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2018,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '118',
  'NumericValue': 118.1636868,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 22326,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ESP',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2007,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '74',
  'NumericValue': 74.03841532,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 22915,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ALB',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2005,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '143',
  'NumericValue': 143.3232563,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 22990,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'COM',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2019,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '180',
  'NumericValue': 179.7729099,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2019',
  'TimeDimensionBegin': '2019-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2019-12-31T00:00:00+01:00'},
 {'Id': 23061,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CRI',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2019,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '112',
  'NumericValue': 111.7075423,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2019',
  'TimeDimensionBegin': '2019-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2019-12-31T00:00:00+01:00'},
 {'Id': 23627,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LCA',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2005,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '99',
  'NumericValue': 99.31699718,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 23789,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LBY',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2013,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '111',
  'NumericValue': 110.6705564,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2013',
  'TimeDimensionBegin': '2013-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2013-12-31T00:00:00+01:00'},
 {'Id': 23868,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BLZ',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2014,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '209',
  'NumericValue': 208.8667805,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 27610,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LTU',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2013,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '265',
  'NumericValue': 265.42968,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2013',
  'TimeDimensionBegin': '2013-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2013-12-31T00:00:00+01:00'},
 {'Id': 27709,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MEX',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2021,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '141',
  'NumericValue': 141.3456353,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2021',
  'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
 {'Id': 28179,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MWI',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2013,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '385',
  'NumericValue': 384.9613712,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2013',
  'TimeDimensionBegin': '2013-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2013-12-31T00:00:00+01:00'},
 {'Id': 28674,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MNG',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2021,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '132',
  'NumericValue': 131.9733665,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2021',
  'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
 {'Id': 29052,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BTN',
  'ParentLocationCode': 'SEAR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'South-East Asia',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2020,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '127',
  'NumericValue': 126.6517463,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 29089,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MMR',
  'ParentLocationCode': 'SEAR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'South-East Asia',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2017,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '192',
  'NumericValue': 192.2848025,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2017',
  'TimeDimensionBegin': '2017-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2017-12-31T00:00:00+01:00'},
 {'Id': 29933,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'NER',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2021,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '229',
  'NumericValue': 229.3428534,
  'Low': None,
  'High': None,
  'Comments': None,
  'Date': '2024-10-31T10:23:48.47+01:00',
  'TimeDimensionValue': '2021',
  'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
 {'Id': 33183,
  'IndicatorCode': 'WHOSIS_000004',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DJI',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',

In [19]:
firstIndicatorDataDataFrame = pd.DataFrame(firstIndicatorData)
firstIndicatorDataDataFrame = firstIndicatorDataDataFrame.loc[firstIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
firstIndicatorDataDataFrame = firstIndicatorDataDataFrame.loc[firstIndicatorDataDataFrame['Dim1'] == 'SEX_BTSX']
firstIndicatorDataDataFrame = firstIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Dim1','Value']]
firstIndicatorDataDataFrame

             Id  IndicatorCode SpatialDim  TimeDim      Dim1 Value
8         14916  WHOSIS_000004        EST     2001  SEX_BTSX   224
9         16254  WHOSIS_000004        SWE     2020  SEX_BTSX    49
16        22326  WHOSIS_000004        ESP     2007  SEX_BTSX    74
36        42203  WHOSIS_000004        BGR     2010  SEX_BTSX   143
66        86423  WHOSIS_000004        CYP     2018  SEX_BTSX    52
...         ...            ...        ...      ...       ...   ...
12886  10122648  WHOSIS_000004        ROU     2003  SEX_BTSX   174
12889  10128530  WHOSIS_000004        DNK     2004  SEX_BTSX    95
12897  10136020  WHOSIS_000004        ROU     2015  SEX_BTSX   136
12900  10141754  WHOSIS_000004        IRL     2012  SEX_BTSX    67
12926  10185773  WHOSIS_000004        SVK     2005  SEX_BTSX   140

[594 rows x 6 columns]

In [20]:
saveToParquet(firstIndicatorDataDataFrame,'adultmortalityratebetween15and60per1000')

In [21]:
secondIndicator = lifeExpectancyIndicatorsDf.iloc[1]
secondIndicator

IndicatorCode                                      WHOSIS_000002
IndicatorName    Healthy life expectancy (HALE) at birth (years)
Language                                                      EN
Category                   Mortality and global health estimates
Name: 1, dtype: object

In [22]:
secondIndicatorData = getData(baseURL,secondIndicator['IndicatorCode'])
secondIndicatorData = secondIndicatorData['value']
secondIndicatorData

[{'Id': 9454832,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'NZL',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 2019,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '69.5 [68.8-70.2]',
  'NumericValue': 69.49638181,
  'Low': 68.77259172,
  'High': 70.24810922,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2019',
  'TimeDimensionBegin': '2019-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2019-12-31T00:00:00+01:00'},
 {'Id': 281,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SVK',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2000,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '61.2 [60.7-61.8]',
  'NumericValue': 61.17224086,
  'Low': 60.7042932,
  'High': 61.81142355,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2000',
  'TimeDimensionBegin': '2000-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2000-12-31T00:00:00+01:00'},
 {'Id': 345,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'REGION',
  'SpatialDim': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': None,
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 2013,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '52.8 [52.1-53.7]',
  'NumericValue': 52.80960902,
  'Low': 52.12596852,
  'High': 53.66439081,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2013',
  'TimeDimensionBegin': '2013-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2013-12-31T00:00:00+01:00'},
 {'Id': 715,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'FRA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2021,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '71.0 [70.1-72.0]',
  'NumericValue': 70.98477826,
  'Low': 70.06015249,
  'High': 71.96159661,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2021',
  'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
 {'Id': 1515,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ECU',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2015,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '65.9 [65.3-66.7]',
  'NumericValue': 65.86762118,
  'Low': 65.31858002,
  'High': 66.66771192,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2015',
  'TimeDimensionBegin': '2015-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2015-12-31T00:00:00+01:00'},
 {'Id': 3657,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MDA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2009,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '63.0 [62.5-63.6]',
  'NumericValue': 63.0482007,
  'Low': 62.45150844,
  'High': 63.64642917,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2009',
  'TimeDimensionBegin': '2009-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2009-12-31T00:00:00+01:00'},
 {'Id': 3947,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'IRQ',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2005,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '59.0 [58.1-60.0]',
  'NumericValue': 59.00025827,
  'Low': 58.14296061,
  'High': 59.95317752,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 4221,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KEN',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2018,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '57.9 [57.1-58.7]',
  'NumericValue': 57.88585027,
  'Low': 57.10910958,
  'High': 58.74800676,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 4377,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DNK',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2000,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '67.4 [66.8-68.2]',
  'NumericValue': 67.42066701,
  'Low': 66.78134959,
  'High': 68.19755358,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2000',
  'TimeDimensionBegin': '2000-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2000-12-31T00:00:00+01:00'},
 {'Id': 4389,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SRB',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2006,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '62.8 [62.3-63.4]',
  'NumericValue': 62.84787161,
  'Low': 62.33477302,
  'High': 63.43937074,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2006',
  'TimeDimensionBegin': '2006-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2006-12-31T00:00:00+01:00'},
 {'Id': 6037,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CHL',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2007,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '67.5 [66.7-68.3]',
  'NumericValue': 67.46124702,
  'Low': 66.69864778,
  'High': 68.32965275,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 7785,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LBN',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2009,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '65.9 [65.2-66.6]',
  'NumericValue': 65.89515043,
  'Low': 65.15211942,
  'High': 66.59750942,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2009',
  'TimeDimensionBegin': '2009-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2009-12-31T00:00:00+01:00'},
 {'Id': 8203,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CAF',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2021,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '43.8 [42.7-45.0]',
  'NumericValue': 43.78474161,
  'Low': 42.74180262,
  'High': 44.96745282,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2021',
  'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
 {'Id': 8494,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TUR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2005,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '64.4 [63.7-65.1]',
  'NumericValue': 64.36681085,
  'Low': 63.68453095,
  'High': 65.0611837,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 10581,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'UGA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2008,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '49.0 [48.3-49.8]',
  'NumericValue': 49.0361303,
  'Low': 48.31116035,
  'High': 49.79283054,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 10647,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GMB',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2011,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '54.7 [54.0-55.6]',
  'NumericValue': 54.74405694,
  'Low': 54.03422631,
  'High': 55.56396458,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2011',
  'TimeDimensionBegin': '2011-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2011-12-31T00:00:00+01:00'},
 {'Id': 13544,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'IDN',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 2018,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '63.9 [63.1-64.8]',
  'NumericValue': 63.88317821,
  'Low': 63.07351507,
  'High': 64.82691924,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 15656,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MUS',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2016,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '64.3 [63.7-65.1]',
  'NumericValue': 64.33615853,
  'Low': 63.70670131,
  'High': 65.08331978,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 15772,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SYC',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2003,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '63.6 [63.0-64.3]',
  'NumericValue': 63.6416111,
  'Low': 63.01041185,
  'High': 64.3338018,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 15773,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MAR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2011,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '62.0 [60.9-63.0]',
  'NumericValue': 61.96295588,
  'Low': 60.93479312,
  'High': 62.98684673,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2011',
  'TimeDimensionBegin': '2011-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2011-12-31T00:00:00+01:00'},
 {'Id': 16156,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'EST',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2017,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '67.9 [67.2-68.5]',
  'NumericValue': 67.86500056,
  'Low': 67.20900792,
  'High': 68.49206268,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2017',
  'TimeDimensionBegin': '2017-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2017-12-31T00:00:00+01:00'},
 {'Id': 18067,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'LCA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2008,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '63.4 [62.8-64.1]',
  'NumericValue': 63.39175695,
  'Low': 62.78801296,
  'High': 64.09164581,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 18087,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GNB',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2019,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '50.6 [49.4-51.8]',
  'NumericValue': 50.60263871,
  'Low': 49.41418209,
  'High': 51.80062171,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2019',
  'TimeDimensionBegin': '2019-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2019-12-31T00:00:00+01:00'},
 {'Id': 18198,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SUR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2015,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '64.7 [63.8-65.6]',
  'NumericValue': 64.74515454,
  'Low': 63.78338487,
  'High': 65.60995819,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2015',
  'TimeDimensionBegin': '2015-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2015-12-31T00:00:00+01:00'},
 {'Id': 18326,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SVK',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2014,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '68.9 [68.1-69.8]',
  'NumericValue': 68.86542829,
  'Low': 68.05116891,
  'High': 69.76246242,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 18938,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SEN',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2001,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '51.5 [50.8-52.3]',
  'NumericValue': 51.54522991,
  'Low': 50.84992743,
  'High': 52.3034097,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2001',
  'TimeDimensionBegin': '2001-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2001-12-31T00:00:00+01:00'},
 {'Id': 18979,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TUR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2009,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '65.2 [64.6-65.9]',
  'NumericValue': 65.20504329,
  'Low': 64.6328287,
  'High': 65.93354298,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2009',
  'TimeDimensionBegin': '2009-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2009-12-31T00:00:00+01:00'},
 {'Id': 19203,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SLV',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2010,
  'Dim1': 'SEX_MLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '61.4 [60.8-62.1]',
  'NumericValue': 61.41962439,
  'Low': 60.79978062,
  'High': 62.10162368,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 20709,
  'IndicatorCode': 'WHOSIS_000002',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AZE',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2005,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '61.6 [60.8-62.3]',
  'NumericValue': 61.55624848,
  'Low': 60.83187251,
  'High': 62.28482236,
  'Comments': None,
  'Date': '2024-08-02T10:11:00.407+02:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 20863,
  'IndicatorCode': 'WHOSIS_000002',

In [23]:
secondIndicatorDataDataFrame = pd.DataFrame(secondIndicatorData)
secondIndicatorDataDataFrame = secondIndicatorDataDataFrame.loc[secondIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
secondIndicatorDataDataFrame = secondIndicatorDataDataFrame.loc[secondIndicatorDataDataFrame['Dim1'] == 'SEX_BTSX']
secondIndicatorDataDataFrame['Value'] = secondIndicatorDataDataFrame['Value'].astype('string')
secondIndicatorDataDataFrame['Value'] = secondIndicatorDataDataFrame['Value'].str.split(' ').str[0]
secondIndicatorDataDataFrame['Value'] = secondIndicatorDataDataFrame['Value'].astype('float')
secondIndicatorDataDataFrame = secondIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Dim1','Value']]
secondIndicatorDataDataFrame

             Id  IndicatorCode SpatialDim  TimeDim      Dim1  Value
20        16156  WHOSIS_000002        EST     2017  SEX_BTSX   67.9
47        32499  WHOSIS_000002        BGR     2010  SEX_BTSX   64.5
52        37159  WHOSIS_000002        EST     2005  SEX_BTSX   63.5
56        38726  WHOSIS_000002        LTU     2014  SEX_BTSX   64.7
77        61677  WHOSIS_000002        LUX     2015  SEX_BTSX   71.1
...         ...            ...        ...      ...       ...    ...
12852  10135601  WHOSIS_000002        NLD     2021  SEX_BTSX   70.0
12862  10142828  WHOSIS_000002        POL     2016  SEX_BTSX   67.5
12893  10171679  WHOSIS_000002        LTU     2007  SEX_BTSX   61.6
12896  10174113  WHOSIS_000002        SVK     2006  SEX_BTSX   64.8
12920  10192627  WHOSIS_000002        IRL     2007  SEX_BTSX   68.4

[594 rows x 6 columns]

In [24]:
saveToParquet(secondIndicatorDataDataFrame,'haleAtBirth')

In [25]:
thirdIndicator = lifeExpectancyIndicatorsDf.iloc[2]
thirdIndicator

IndicatorCode                            WHOSIS_000001
IndicatorName         Life expectancy at birth (years)
Language                                            EN
Category         Mortality and global health estimates
Name: 2, dtype: object

In [26]:
thirdIndicatorData = getData(baseURL,thirdIndicator['IndicatorCode'])
thirdIndicatorData = thirdIndicatorData['value']
thirdIndicatorData

[{'Id': 871,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SOM',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2008,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '48.0 [46.7-49.6]',
  'NumericValue': 48.03754082,
  'Low': 46.71678387,
  'High': 49.62845721,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 1065,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BTN',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'SEAR',
  'ParentLocation': 'South-East Asia',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2002,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '67.8 [67.1-68.6]',
  'NumericValue': 67.84566543,
  'Low': 67.08312422,
  'High': 68.55874474,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2002',
  'TimeDimensionBegin': '2002-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2002-12-31T00:00:00+01:00'},
 {'Id': 3596,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BHR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2011,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '75.2 [75.1-75.4]',
  'NumericValue': 75.20535884,
  'Low': 75.05047771,
  'High': 75.38517504,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2011',
  'TimeDimensionBegin': '2011-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2011-12-31T00:00:00+01:00'},
 {'Id': 6877,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SAU',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2005,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '73.1 [72.8-73.5]',
  'NumericValue': 73.12227378,
  'Low': 72.80645298,
  'High': 73.47894822,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 7129,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CYP',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2003,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '76.9 [76.7-77.2]',
  'NumericValue': 76.86012885,
  'Low': 76.67123665,
  'High': 77.16347738,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 7447,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DNK',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2014,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '78.6 [78.6-78.7]',
  'NumericValue': 78.61687489,
  'Low': 78.59347689,
  'High': 78.7057478,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 8748,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PHL',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2007,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '69.6 [69.3-70.0]',
  'NumericValue': 69.58190674,
  'Low': 69.27042318,
  'High': 69.99117192,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 9286,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MAR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2020,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '73.9 [73.3-74.4]',
  'NumericValue': 73.86985157,
  'Low': 73.33215257,
  'High': 74.42699856,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 10246,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'WSM',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2004,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '72.1 [71.6-72.7]',
  'NumericValue': 72.08095548,
  'Low': 71.56647872,
  'High': 72.73081838,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2004',
  'TimeDimensionBegin': '2004-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2004-12-31T00:00:00+01:00'},
 {'Id': 11603,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'JOR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2014,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '78.4 [78.0-78.9]',
  'NumericValue': 78.39096907,
  'Low': 77.9773549,
  'High': 78.89185172,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2014',
  'TimeDimensionBegin': '2014-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2014-12-31T00:00:00+01:00'},
 {'Id': 12978,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'URY',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2015,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '77.1 [77.1-77.2]',
  'NumericValue': 77.09925201,
  'Low': 77.05355529,
  'High': 77.20308276,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2015',
  'TimeDimensionBegin': '2015-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2015-12-31T00:00:00+01:00'},
 {'Id': 12981,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DNK',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2020,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '83.2 [83.1-83.3]',
  'NumericValue': 83.16166983,
  'Low': 83.13841156,
  'High': 83.25733665,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 13025,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PRI',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2020,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '76.1 [76.1-76.3]',
  'NumericValue': 76.14090106,
  'Low': 76.05102592,
  'High': 76.30635768,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 14139,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GHA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2005,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '58.3 [57.7-59.0]',
  'NumericValue': 58.2958344,
  'Low': 57.73964597,
  'High': 59.00903347,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 14988,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TON',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2019,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '72.9 [72.4-73.6]',
  'NumericValue': 72.94212581,
  'Low': 72.39303564,
  'High': 73.64425455,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2019',
  'TimeDimensionBegin': '2019-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2019-12-31T00:00:00+01:00'},
 {'Id': 16632,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'JOR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2009,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '76.6 [76.2-76.9]',
  'NumericValue': 76.55739127,
  'Low': 76.24832572,
  'High': 76.90901942,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2009',
  'TimeDimensionBegin': '2009-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2009-12-31T00:00:00+01:00'},
 {'Id': 16838,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TUR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2012,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '73.8 [73.4-74.2]',
  'NumericValue': 73.77355049,
  'Low': 73.35270086,
  'High': 74.18741879,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 17728,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BRA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2003,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '72.3 [72.0-72.6]',
  'NumericValue': 72.30491342,
  'Low': 72.02894266,
  'High': 72.58864374,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 17825,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'FJI',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2006,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '67.1 [66.8-67.4]',
  'NumericValue': 67.08069927,
  'Low': 66.83476265,
  'High': 67.36102486,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2006',
  'TimeDimensionBegin': '2006-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2006-12-31T00:00:00+01:00'},
 {'Id': 18700,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'NIC',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2020,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '71.7 [71.4-72.1]',
  'NumericValue': 71.71241065,
  'Low': 71.39890481,
  'High': 72.07787079,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 19666,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'IRQ',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2003,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '65.7 [64.9-66.6]',
  'NumericValue': 65.68953983,
  'Low': 64.89438575,
  'High': 66.62662104,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 20877,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BGD',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'SEAR',
  'ParentLocation': 'South-East Asia',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2017,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '72.1 [71.5-72.9]',
  'NumericValue': 72.08322327,
  'Low': 71.46217486,
  'High': 72.89170185,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2017',
  'TimeDimensionBegin': '2017-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2017-12-31T00:00:00+01:00'},
 {'Id': 21055,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TON',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2016,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '72.6 [71.9-73.2]',
  'NumericValue': 72.56032607,
  'Low': 71.92825937,
  'High': 73.19726025,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 21090,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SWE',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2016,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '80.4 [80.4-80.4]',
  'NumericValue': 80.36714012,
  'Low': 80.36303372,
  'High': 80.44718723,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 21977,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'GLOBAL',
  'SpatialDim': 'GLOBAL',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': None,
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2015,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '72.2 [71.7-72.7]',
  'NumericValue': 72.18568947,
  'Low': 71.71225781,
  'High': 72.66885564,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2015',
  'TimeDimensionBegin': '2015-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2015-12-31T00:00:00+01:00'},
 {'Id': 22954,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AUS',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2006,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '81.0 [81.0-81.1]',
  'NumericValue': 81.04245453,
  'Low': 81.03700874,
  'High': 81.11608627,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2006',
  'TimeDimensionBegin': '2006-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2006-12-31T00:00:00+01:00'},
 {'Id': 23215,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ISL',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2005,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '80.9 [80.8-81.1]',
  'NumericValue': 80.90304444,
  'Low': 80.80183544,
  'High': 81.10646149,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 23223,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'COD',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2018,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '63.6 [62.7-64.6]',
  'NumericValue': 63.60932257,
  'Low': 62.68629835,
  'High': 64.59326208,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 24448,
  'IndicatorCode': 'WHOSIS_000001',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'FSM',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2001,
  'Dim2Type': None,
  'Dim2': None,
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '63.8 [63.2-64.5]',
  'NumericValue': 63.81961029,
  'Low': 63.18020379,
  'High': 64.49686133,
  'Comments': None,
  'Date': '2024-08-02T09:43:39.193+02:00',
  'TimeDimensionValue': '2001',

In [27]:
thirdIndicatorDataDataFrame = pd.DataFrame(thirdIndicatorData)
thirdIndicatorDataDataFrame = thirdIndicatorDataDataFrame.loc[thirdIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
thirdIndicatorDataDataFrame = thirdIndicatorDataDataFrame.loc[thirdIndicatorDataDataFrame['Dim1'] == 'SEX_BTSX']
thirdIndicatorDataDataFrame['Value'] = thirdIndicatorDataDataFrame['Value'].astype('string')
thirdIndicatorDataDataFrame['Value'] = thirdIndicatorDataDataFrame['Value'].str.split(' ').str[0]
thirdIndicatorDataDataFrame['Value'] = thirdIndicatorDataDataFrame['Value'].astype('float')
thirdIndicatorDataDataFrame = thirdIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Dim1','Value']]
thirdIndicatorDataDataFrame

             Id  IndicatorCode SpatialDim  TimeDim      Dim1  Value
71        59333  WHOSIS_000001        CYP     2010  SEX_BTSX   81.2
73        60532  WHOSIS_000001        MLT     2017  SEX_BTSX   82.1
83        71458  WHOSIS_000001        DNK     2013  SEX_BTSX   80.2
90        80280  WHOSIS_000001        HRV     2003  SEX_BTSX   74.9
91        80468  WHOSIS_000001        LTU     2003  SEX_BTSX   71.8
...         ...            ...        ...      ...       ...    ...
12831  10131572  WHOSIS_000001        HUN     2000  SEX_BTSX   71.4
12839  10137983  WHOSIS_000001        HUN     2009  SEX_BTSX   74.2
12856  10152241  WHOSIS_000001        IRL     2009  SEX_BTSX   79.5
12922  10192327  WHOSIS_000001        MLT     2010  SEX_BTSX   80.5
12924  10195471  WHOSIS_000001        GRC     2007  SEX_BTSX   79.5

[594 rows x 6 columns]

In [28]:
saveToParquet(thirdIndicatorDataDataFrame,'lifeexpetancyatbirth')

In [29]:
fourthIndicator = lifeExpectancyIndicatorsDf.iloc[3]
fourthIndicator

IndicatorCode                                       MDG_0000000007
IndicatorName    Under-five mortality rate (probability of dyin...
Language                                                        EN
Category                       Child mortality and causes of death
Name: 3, dtype: object

In [30]:
fourthIndicatorData = getData(baseURL,fourthIndicator['IndicatorCode'])
fourthIndicatorData = fourthIndicatorData['value']
fourthIndicatorData

[{'Id': 9454885,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DMA',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2022,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '32.8 [28.4-38.0]',
  'NumericValue': 32.81284074,
  'Low': 28.401476804,
  'High': 38.035805741,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 9455009,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TON',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 1995,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_WQ4',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '16.5 [13.0-20.6]',
  'NumericValue': 16.492516372,
  'Low': 12.957305384,
  'High': 20.63364014,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '1995',
  'TimeDimensionBegin': '1995-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1995-12-31T00:00:00+01:00'},
 {'Id': 9455040,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DMA',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2010,
  'Dim1': 'SEX_MLE',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '26.5 [24.4-28.7]',
  'NumericValue': 26.452975132,
  'Low': 24.41876592,
  'High': 28.735300196,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '2010',
  'TimeDimensionBegin': '2010-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2010-12-31T00:00:00+01:00'},
 {'Id': 9455150,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CAF',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 1960,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '283.1 [223.5-372.4]',
  'NumericValue': 283.13568606,
  'Low': 223.476292476,
  'High': 372.386718401,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '1960',
  'TimeDimensionBegin': '1960-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1960-12-31T00:00:00+01:00'},
 {'Id': 9455584,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'VNM',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 2018,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_WQ4',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '17.0 [14.2-20.1]',
  'NumericValue': 17.028475886,
  'Low': 14.24058247,
  'High': 20.0992884,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 9455630,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AUT',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 1993,
  'Dim1': 'SEX_MLE',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '8.8 [8.5-9.1]',
  'NumericValue': 8.792211985,
  'Low': 8.512351515,
  'High': 9.081469347,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '1993',
  'TimeDimensionBegin': '1993-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1993-12-31T00:00:00+01:00'},
 {'Id': 9455639,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'UKR',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 1983,
  'Dim1': 'SEX_MLE',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '26.4 [22.5-31.8]',
  'NumericValue': 26.4180155,
  'Low': 22.491484805,
  'High': 31.764638207,
  'Comments': 'The State Statistics Service of Ukraine (SSSU) have suspended the compilation of impartial statistical information on births and deaths starting from 2022 and on the number of population starting from data as of January 1, 2023, onwards. Consequently, no data is available for 2022.',
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '1983',
  'TimeDimensionBegin': '1983-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1983-12-31T00:00:00+01:00'},
 {'Id': 9455746,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'GLOBAL',
  'SpatialDim': 'GLOBAL',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 1987,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '97.0 [95.4-98.8]',
  'NumericValue': 97.002005751,
  'Low': 95.440719415,
  'High': 98.844781474,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '1987',
  'TimeDimensionBegin': '1987-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1987-12-31T00:00:00+01:00'},
 {'Id': 9455819,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KWT',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 1959,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '145.4 [111.2-191.8]',
  'NumericValue': 145.440727271,
  'Low': 111.196535566,
  'High': 191.815919886,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '1959',
  'TimeDimensionBegin': '1959-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1959-12-31T00:00:00+01:00'},
 {'Id': 9455888,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BIH',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 1993,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '58.7 [56.0-61.4]',
  'NumericValue': 58.664306459,
  'Low': 55.996556861,
  'High': 61.432525726,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '1993',
  'TimeDimensionBegin': '1993-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1993-12-31T00:00:00+01:00'},
 {'Id': 9455898,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DZA',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 1978,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '177.2 [168.6-186.4]',
  'NumericValue': 177.188510591,
  'Low': 168.64407697,
  'High': 186.425994522,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '1978',
  'TimeDimensionBegin': '1978-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1978-12-31T00:00:00+01:00'},
 {'Id': 136,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GIN',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2005,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '136.6 [126.6-147.3]',
  'NumericValue': 136.64315336,
  'Low': 126.555646663,
  'High': 147.346121625,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 752,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SLV',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2017,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_WQ5',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '9.2 [5.8-14.3]',
  'NumericValue': 9.177680912,
  'Low': 5.84183654,
  'High': 14.255143372,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '2017',
  'TimeDimensionBegin': '2017-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2017-12-31T00:00:00+01:00'},
 {'Id': 1014,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GRD',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 1975,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '42.5 [37.6-48.1]',
  'NumericValue': 42.533506679,
  'Low': 37.60871237,
  'High': 48.113130124,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '1975',
  'TimeDimensionBegin': '1975-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1975-12-31T00:00:00+01:00'},
 {'Id': 1064,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'FJI',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 1992,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_WQ1',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '35.0 [27.5-43.3]',
  'NumericValue': 35.047869775,
  'Low': 27.465776811,
  'High': 43.250896974,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '1992',
  'TimeDimensionBegin': '1992-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1992-12-31T00:00:00+01:00'},
 {'Id': 1183,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'IRN',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2003,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '30.2 [27.1-33.8]',
  'NumericValue': 30.219665851,
  'Low': 27.078690115,
  'High': 33.771218098,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 1645,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MOZ',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2011,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_WQ3',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '93.3 [84.0-103.0]',
  'NumericValue': 93.342799443,
  'Low': 83.961474059,
  'High': 103.001955898,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '2011',
  'TimeDimensionBegin': '2011-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2011-12-31T00:00:00+01:00'},
 {'Id': 1917,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BRN',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 1978,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '27.1 [25.1-29.1]',
  'NumericValue': 27.052325152,
  'Low': 25.137646079,
  'High': 29.078873941,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '1978',
  'TimeDimensionBegin': '1978-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1978-12-31T00:00:00+01:00'},
 {'Id': 1960,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MAR',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2020,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_WQ5',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '10.4 [6.9-15.2]',
  'NumericValue': 10.386219871,
  'Low': 6.88221101,
  'High': 15.195882748,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 2106,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BHS',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2008,
  'Dim1': 'SEX_MLE',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '17.3 [16.2-18.5]',
  'NumericValue': 17.318466612,
  'Low': 16.163974894,
  'High': 18.523133348,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 2528,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TUR',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 1968,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '192.6 [179.2-207.5]',
  'NumericValue': 192.606922792,
  'Low': 179.204068471,
  'High': 207.453316686,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '1968',
  'TimeDimensionBegin': '1968-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1968-12-31T00:00:00+01:00'},
 {'Id': 2634,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'UKR',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2007,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '11.9 [11.1-12.7]',
  'NumericValue': 11.92241936,
  'Low': 11.148901188,
  'High': 12.708587319,
  'Comments': 'The State Statistics Service of Ukraine (SSSU) have suspended the compilation of impartial statistical information on births and deaths starting from 2022 and on the number of population starting from data as of January 1, 2023, onwards. Consequently, no data is available for 2022.',
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 2690,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CMR',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2000,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_WQ2',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '166.9 [150.8-184.6]',
  'NumericValue': 166.86343221,
  'Low': 150.806113008,
  'High': 184.579319997,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '2000',
  'TimeDimensionBegin': '2000-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2000-12-31T00:00:00+01:00'},
 {'Id': 2766,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BRA',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2022,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_WQ1',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '21.6 [17.7-26.0]',
  'NumericValue': 21.60574685,
  'Low': 17.688643705,
  'High': 25.997659243,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 2857,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'UGA',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2006,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_WQ4',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '99.2 [89.2-110.1]',
  'NumericValue': 99.159687649,
  'Low': 89.20242142,
  'High': 110.088190842,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '2006',
  'TimeDimensionBegin': '2006-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2006-12-31T00:00:00+01:00'},
 {'Id': 2920,
  'IndicatorCode': 'MDG_0000000007',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KIR',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 1974,
  'Dim1': 'SEX_FMLE',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARSUNDER5',
  'Dim3Type': 'WEALTHQUINTILE',
  'Dim3': 'WEALTHQUINTILE_TOTL',
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '119.7 [104.7-136.4]',
  'NumericValue': 119.711293613,
  'Low': 104.734515426,
  'High': 136.419751249,
  'Comments': None,
  'Date': '2025-04-15T12:59:44.083+02:00',
  'TimeDimensionValue': '1974',
  'TimeDimensionBegin': '1974-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1974-12-31T00:00:00+01:00'},
 {'Id': 3485,

In [35]:
fourthIndicatorDataDataFrame = pd.DataFrame(fourthIndicatorData)
fourthIndicatorDataDataFrame = fourthIndicatorDataDataFrame.loc[fourthIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
fourthIndicatorDataDataFrame = fourthIndicatorDataDataFrame.loc[fourthIndicatorDataDataFrame['Dim1'] == 'SEX_BTSX']
fourthIndicatorDataDataFrame['Value'] = fourthIndicatorDataDataFrame['Value'].astype('string')
fourthIndicatorDataDataFrame['Value'] = fourthIndicatorDataDataFrame['Value'].str.split(' ').str[0]
fourthIndicatorDataDataFrame['Value'] = fourthIndicatorDataDataFrame['Value'].astype('float')
fourthIndicatorDataDataFrame = fourthIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Dim1','Value']]
fourthIndicatorDataDataFrame

             Id   IndicatorCode SpatialDim  TimeDim      Dim1  Value
65        11306  MDG_0000000007        ESP     1997  SEX_BTSX    6.1
91        16349  MDG_0000000007        BEL     1954  SEX_BTSX   48.1
144       23113  MDG_0000000007        FRA     1990  SEX_BTSX    9.0
166       26559  MDG_0000000007        CYP     1988  SEX_BTSX   11.3
224       36329  MDG_0000000007        HUN     1998  SEX_BTSX   11.1
...         ...             ...        ...      ...       ...    ...
62972  10187750  MDG_0000000007        SVK     1970  SEX_BTSX   29.5
62976  10188500  MDG_0000000007        AUT     1968  SEX_BTSX   29.8
62978  10188599  MDG_0000000007        POL     1982  SEX_BTSX   22.6
62979  10188794  MDG_0000000007        AUT     1962  SEX_BTSX   37.9
63002  10193851  MDG_0000000007        LUX     1995  SEX_BTSX    6.4

[1826 rows x 6 columns]

In [38]:
saveToParquet(fourthIndicatorDataDataFrame,'underfivemortalityrate')

In [37]:
fifthIndicator = lifeExpectancyIndicatorsDf.iloc[4]
fifthIndicator

IndicatorCode                                     WHOSIS_000003
IndicatorName    Neonatal mortality rate (per 1000 live births)
Language                                                     EN
Category                    Child mortality and causes of death
Name: 4, dtype: object

In [39]:
fifthIndicatorData = getData(baseURL,fifthIndicator['IndicatorCode'])
fifthIndicatorData = fifthIndicatorData['value']
fifthIndicatorData

[{'Id': 9455167,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'UNICEFREGION',
  'SpatialDim': 'UNICEFREGIONEAP',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': None,
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 2005,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '14.9 [14.2-15.7]',
  'NumericValue': 14.899013971,
  'Low': 14.187388317,
  'High': 15.667195177,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 639,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'WORLDBANKINCOMEGROUP',
  'SpatialDim': 'WB_HI',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': None,
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 2007,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '3.8 [3.7-3.9]',
  'NumericValue': 3.791280357,
  'Low': 3.676227685,
  'High': 3.918320218,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 657,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CHE',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 1960,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '16.3 [15.8-16.8]',
  'NumericValue': 16.340479056,
  'Low': 15.847232297,
  'High': 16.821884506,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '1960',
  'TimeDimensionBegin': '1960-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1960-12-31T00:00:00+01:00'},
 {'Id': 5000,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SOM',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2018,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '38.2 [18.7-79.2]',
  'NumericValue': 38.231089255,
  'Low': 18.682185929,
  'High': 79.190501776,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2018',
  'TimeDimensionBegin': '2018-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2018-12-31T00:00:00+01:00'},
 {'Id': 5471,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'MGHEREG',
  'SpatialDim': 'UNICEF_ROSA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': None,
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 2019,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '25.3 [23.8-27.0]',
  'NumericValue': 25.328511423,
  'Low': 23.791621514,
  'High': 27.007903132,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2019',
  'TimeDimensionBegin': '2019-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2019-12-31T00:00:00+01:00'},
 {'Id': 6460,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BFA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2009,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '31.8 [26.4-37.8]',
  'NumericValue': 31.789127644,
  'Low': 26.407445956,
  'High': 37.845054967,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2009',
  'TimeDimensionBegin': '2009-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2009-12-31T00:00:00+01:00'},
 {'Id': 6649,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TCA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 1998,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '6.3 [4.0-9.3]',
  'NumericValue': 6.303571981,
  'Low': 4.03870569,
  'High': 9.337169199,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '1998',
  'TimeDimensionBegin': '1998-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1998-12-31T00:00:00+01:00'},
 {'Id': 7615,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MDA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2022,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '10.8 [8.1-14.5]',
  'NumericValue': 10.820595628,
  'Low': 8.118221916,
  'High': 14.479794365,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 7711,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'NAM',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 1985,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '31.3 [26.8-36.4]',
  'NumericValue': 31.327641871,
  'Low': 26.82224609,
  'High': 36.370386444,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '1985',
  'TimeDimensionBegin': '1985-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1985-12-31T00:00:00+01:00'},
 {'Id': 11041,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'AND',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2016,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1.7 [0.5-5.5]',
  'NumericValue': 1.705516543,
  'Low': 0.535840807,
  'High': 5.520521357,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2016',
  'TimeDimensionBegin': '2016-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2016-12-31T00:00:00+01:00'},
 {'Id': 11774,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MCO',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2003,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '2.5 [1.7-3.4]',
  'NumericValue': 2.535631127,
  'Low': 1.683951665,
  'High': 3.383040591,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 12544,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ISL',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 1985,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.2 [3.7-4.7]',
  'NumericValue': 4.189447324,
  'Low': 3.724011471,
  'High': 4.709486165,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '1985',
  'TimeDimensionBegin': '1985-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1985-12-31T00:00:00+01:00'},
 {'Id': 12845,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'IDN',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'WPR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'TimeDim': 2001,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '22.0 [20.3-23.6]',
  'NumericValue': 21.975128333,
  'Low': 20.316703818,
  'High': 23.645624244,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2001',
  'TimeDimensionBegin': '2001-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2001-12-31T00:00:00+01:00'},
 {'Id': 14461,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'UNSDGREGION',
  'SpatialDim': 'UNSDG_CENTRALASIASOUTHERNASIA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': None,
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'TimeDim': 2012,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '31.3 [30.0-32.7]',
  'NumericValue': 31.274350647,
  'Low': 29.963641144,
  'High': 32.683496131,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2012',
  'TimeDimensionBegin': '2012-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2012-12-31T00:00:00+01:00'},
 {'Id': 14867,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'NAM',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2002,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '17.9 [15.7-20.4]',
  'NumericValue': 17.946520883,
  'Low': 15.728051584,
  'High': 20.436090317,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2002',
  'TimeDimensionBegin': '2002-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2002-12-31T00:00:00+01:00'},
 {'Id': 15415,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'NOR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EUR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'TimeDim': 2011,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1.8 [1.7-1.9]',
  'NumericValue': 1.801706508,
  'Low': 1.685552179,
  'High': 1.925101496,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2011',
  'TimeDimensionBegin': '2011-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2011-12-31T00:00:00+01:00'},
 {'Id': 15549,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'URY',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 1981,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '16.8 [13.1-20.4]',
  'NumericValue': 16.791486805,
  'Low': 13.112972187,
  'High': 20.43039437,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '1981',
  'TimeDimensionBegin': '1981-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1981-12-31T00:00:00+01:00'},
 {'Id': 15894,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'NER',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2013,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '34.6 [29.8-40.3]',
  'NumericValue': 34.628253025,
  'Low': 29.768188556,
  'High': 40.320739259,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2013',
  'TimeDimensionBegin': '2013-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2013-12-31T00:00:00+01:00'},
 {'Id': 18706,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'COG',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 1983,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '29.3 [23.9-36.2]',
  'NumericValue': 29.258211707,
  'Low': 23.884847774,
  'High': 36.182483184,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '1983',
  'TimeDimensionBegin': '1983-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1983-12-31T00:00:00+01:00'},
 {'Id': 19415,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ARG',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 1972,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '23.9 [20.6-27.5]',
  'NumericValue': 23.9469854,
  'Low': 20.550396029,
  'High': 27.499742517,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '1972',
  'TimeDimensionBegin': '1972-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1972-12-31T00:00:00+01:00'},
 {'Id': 20417,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'JAM',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 1993,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '17.7 [14.7-21.4]',
  'NumericValue': 17.735758314,
  'Low': 14.743315242,
  'High': 21.356514832,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '1993',
  'TimeDimensionBegin': '1993-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1993-12-31T00:00:00+01:00'},
 {'Id': 20784,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ECU',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2004,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '11.7 [9.9-13.7]',
  'NumericValue': 11.681848523,
  'Low': 9.898599715,
  'High': 13.650816501,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2004',
  'TimeDimensionBegin': '2004-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2004-12-31T00:00:00+01:00'},
 {'Id': 20860,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TUN',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 2004,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '13.8 [12.3-15.5]',
  'NumericValue': 13.829837554,
  'Low': 12.265886165,
  'High': 15.514146198,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2004',
  'TimeDimensionBegin': '2004-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2004-12-31T00:00:00+01:00'},
 {'Id': 21703,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MSR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AMR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'TimeDim': 2022,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '3.5 [1.2-9.9]',
  'NumericValue': 3.500170715,
  'Low': 1.202221606,
  'High': 9.878113823,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 21896,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DZA',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 1970,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '70.9 [59.1-84.3]',
  'NumericValue': 70.850414728,
  'Low': 59.103331752,
  'High': 84.308349158,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '1970',
  'TimeDimensionBegin': '1970-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1970-12-31T00:00:00+01:00'},
 {'Id': 22341,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MAR',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 1960,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '67.5 [58.3-78.1]',
  'NumericValue': 67.530466755,
  'Low': 58.27220385,
  'High': 78.07608723,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '1960',
  'TimeDimensionBegin': '1960-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1960-12-31T00:00:00+01:00'},
 {'Id': 22671,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SSD',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'AFR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'TimeDim': 2001,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '55.2 [41.4-72.9]',
  'NumericValue': 55.193601362,
  'Low': 41.404168331,
  'High': 72.855792684,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '2001',
  'TimeDimensionBegin': '2001-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2001-12-31T00:00:00+01:00'},
 {'Id': 22919,
  'IndicatorCode': 'WHOSIS_000003',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SDN',
  'TimeDimType': 'YEAR',
  'ParentLocationCode': 'EMR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'TimeDim': 1977,
  'Dim1': 'SEX_BTSX',
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_DAYS0-27',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '45.5 [40.3-50.7]',
  'NumericValue': 45.462993752,
  'Low': 40.291127105,
  'High': 50.744919287,
  'Comments': None,
  'Date': '2025-04-15T16:15:21.28+02:00',
  'TimeDimensionValue': '1977',
  'TimeDimensionBegin': '1977-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1977-12-31T00:00:00+01:00'},
 {'Id': 23239,
  'IndicatorCode': 'WHOSIS_000003',

In [40]:
fifthIndicatorDataDataFrame = pd.DataFrame(fifthIndicatorData)
fifthIndicatorDataDataFrame = fifthIndicatorDataDataFrame.loc[fifthIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
fifthIndicatorDataDataFrame = fifthIndicatorDataDataFrame.loc[fifthIndicatorDataDataFrame['Dim1'] == 'SEX_BTSX']
fifthIndicatorDataDataFrame['Value'] = fifthIndicatorDataDataFrame['Value'].astype('string')
fifthIndicatorDataDataFrame['Value'] = fifthIndicatorDataDataFrame['Value'].str.split(' ').str[0]
fifthIndicatorDataDataFrame['Value'] = fifthIndicatorDataDataFrame['Value'].astype('float')
fifthIndicatorDataDataFrame = fifthIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Dim1','Value']]
fifthIndicatorDataDataFrame

             Id  IndicatorCode SpatialDim  TimeDim      Dim1  Value
29        29247  WHOSIS_000003        AUT     1991  SEX_BTSX    4.4
32        31529  WHOSIS_000003        HRV     2020  SEX_BTSX    2.9
41        36081  WHOSIS_000003        POL     1970  SEX_BTSX   18.3
48        42565  WHOSIS_000003        POL     1981  SEX_BTSX   13.8
54        49925  WHOSIS_000003        LTU     1999  SEX_BTSX    4.8
...         ...            ...        ...      ...       ...    ...
11783  10133827  WHOSIS_000003        FIN     1982  SEX_BTSX    4.5
11795  10145198  WHOSIS_000003        ROU     2022  SEX_BTSX    3.2
11832  10174716  WHOSIS_000003        MLT     2009  SEX_BTSX    4.6
11864  10196434  WHOSIS_000003        ITA     1960  SEX_BTSX   24.7
11872  10205821  WHOSIS_000003        IRL     2004  SEX_BTSX    3.3

[1481 rows x 6 columns]

In [41]:
saveToParquet(fifthIndicatorDataDataFrame,'neonatalMortalityRate')

In [42]:
sixthIndicator = lifeExpectancyIndicatorsDf.iloc[5]
sixthIndicator

IndicatorCode                                              MORTADO
IndicatorName    Adolescent mortality rate (per 1 000 age speci...
Language                                                        EN
Category                       Child mortality and causes of death
Name: 5, dtype: object

In [44]:
sixthIndicatorData = getData(baseURL,sixthIndicator['IndicatorCode'])
sixthIndicatorData = sixthIndicatorData['value']
sixthIndicatorData

[{'Id': 9454801,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SVK',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2022,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-14',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '0.7 [0.6-0.9]',
  'NumericValue': 0.720128232,
  'Low': 0.589192267,
  'High': 0.86507728,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2022',
  'TimeDimensionBegin': '2022-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2022-12-31T00:00:00+01:00'},
 {'Id': 9455166,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'KAZ',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 1996,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS15-19',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '8.9 [8.7-9.1]',
  'NumericValue': 8.914588687,
  'Low': 8.672978632,
  'High': 9.144754839,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '1996',
  'TimeDimensionBegin': '1996-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1996-12-31T00:00:00+01:00'},
 {'Id': 9455189,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ARG',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2005,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS15-19',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '2.1 [2.0-2.2]',
  'NumericValue': 2.117147891,
  'Low': 2.025614617,
  'High': 2.211620482,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 9455205,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'EST',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2002,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-14',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1.4 [1.2-1.6]',
  'NumericValue': 1.397871695,
  'Low': 1.170325828,
  'High': 1.643613316,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2002',
  'TimeDimensionBegin': '2002-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2002-12-31T00:00:00+01:00'},
 {'Id': 9455260,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MAR',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2023,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-14',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1.3 [0.3-3.6]',
  'NumericValue': 1.300465507,
  'Low': 0.264221891,
  'High': 3.557911585,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2023',
  'TimeDimensionBegin': '2023-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2023-12-31T00:00:00+01:00'},
 {'Id': 9455293,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DEU',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2005,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS15-19',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1.7 [1.6-1.7]',
  'NumericValue': 1.662395911,
  'Low': 1.638871902,
  'High': 1.685097083,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 9455339,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ARE',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2004,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-14',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1.1 [0.9-1.5]',
  'NumericValue': 1.137862509,
  'Low': 0.885240373,
  'High': 1.461573046,
  'Comments': 'The UN IGME estimates are not the official statistics of the United Arab Emirates.',
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2004',
  'TimeDimensionBegin': '2004-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2004-12-31T00:00:00+01:00'},
 {'Id': 9455348,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SYR',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2007,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-14',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1.4 [1.3-1.5]',
  'NumericValue': 1.388148991,
  'Low': 1.307612025,
  'High': 1.469109496,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2007',
  'TimeDimensionBegin': '2007-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2007-12-31T00:00:00+01:00'},
 {'Id': 9455373,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'TTO',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 1997,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-14',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1.6 [1.3-1.8]',
  'NumericValue': 1.551233996,
  'Low': 1.338016978,
  'High': 1.776220409,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '1997',
  'TimeDimensionBegin': '1997-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1997-12-31T00:00:00+01:00'},
 {'Id': 9455376,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'DJI',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 1999,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-19',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '24.8 [18.8-32.4]',
  'NumericValue': 24.803894904,
  'Low': 18.779102863,
  'High': 32.356643768,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '1999',
  'TimeDimensionBegin': '1999-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1999-12-31T00:00:00+01:00'},
 {'Id': 9455526,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'NOR',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2019,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-14',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '0.4 [0.4-0.5]',
  'NumericValue': 0.435077924,
  'Low': 0.365380128,
  'High': 0.510193846,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2019',
  'TimeDimensionBegin': '2019-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2019-12-31T00:00:00+01:00'},
 {'Id': 9455560,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'ARE',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 1995,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-14',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1.7 [1.3-2.1]',
  'NumericValue': 1.657537502,
  'Low': 1.281975357,
  'High': 2.139525604,
  'Comments': 'The UN IGME estimates are not the official statistics of the United Arab Emirates.',
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '1995',
  'TimeDimensionBegin': '1995-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1995-12-31T00:00:00+01:00'},
 {'Id': 9455706,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'REGION',
  'SpatialDim': 'AFR',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2004,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS15-19',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '12.8 [12.3-13.5]',
  'NumericValue': 12.798631881,
  'Low': 12.277823782,
  'High': 13.464307328,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2004',
  'TimeDimensionBegin': '2004-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2004-12-31T00:00:00+01:00'},
 {'Id': 63,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PRT',
  'ParentLocationCode': 'EUR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Europe',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 1992,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-14',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '2.3 [2.1-2.4]',
  'NumericValue': 2.274631692,
  'Low': 2.111455713,
  'High': 2.439322687,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '1992',
  'TimeDimensionBegin': '1992-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1992-12-31T00:00:00+01:00'},
 {'Id': 85,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'VCT',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 1997,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS15-19',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '2.1 [1.7-2.7]',
  'NumericValue': 2.140201512,
  'Low': 1.658336302,
  'High': 2.734352597,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '1997',
  'TimeDimensionBegin': '1997-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1997-12-31T00:00:00+01:00'},
 {'Id': 104,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'QAT',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2000,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-14',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1.2 [1.0-1.4]',
  'NumericValue': 1.184233775,
  'Low': 0.95257195,
  'High': 1.446940047,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2000',
  'TimeDimensionBegin': '2000-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2000-12-31T00:00:00+01:00'},
 {'Id': 134,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'PRY',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 1992,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS15-19',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '8.9 [6.9-11.5]',
  'NumericValue': 8.896382807,
  'Low': 6.850747458,
  'High': 11.548086354,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '1992',
  'TimeDimensionBegin': '1992-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1992-12-31T00:00:00+01:00'},
 {'Id': 174,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'MGHEREG',
  'SpatialDim': 'UNICEF_EAPRO',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2020,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-14',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1.7 [1.2-2.4]',
  'NumericValue': 1.664529423,
  'Low': 1.244887728,
  'High': 2.435444602,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2020',
  'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
 {'Id': 246,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'YEM',
  'ParentLocationCode': 'EMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Eastern Mediterranean',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2000,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-19',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '11.1 [8.5-14.0]',
  'NumericValue': 11.116600097,
  'Low': 8.461706268,
  'High': 13.984853476,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2000',
  'TimeDimensionBegin': '2000-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2000-12-31T00:00:00+01:00'},
 {'Id': 374,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'GUY',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2019,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-19',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '7.5 [6.8-8.3]',
  'NumericValue': 7.503321673,
  'Low': 6.825129864,
  'High': 8.257439772,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2019',
  'TimeDimensionBegin': '2019-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2019-12-31T00:00:00+01:00'},
 {'Id': 588,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BRB',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2003,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS15-19',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '3.6 [3.1-4.1]',
  'NumericValue': 3.576757663,
  'Low': 3.12968712,
  'High': 4.070376456,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2003',
  'TimeDimensionBegin': '2003-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2003-12-31T00:00:00+01:00'},
 {'Id': 683,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'BRN',
  'ParentLocationCode': 'WPR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Western Pacific',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 2005,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS15-19',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '2.3 [2.0-2.6]',
  'NumericValue': 2.27700579,
  'Low': 2.02146223,
  'High': 2.56049106,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2005',
  'TimeDimensionBegin': '2005-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2005-12-31T00:00:00+01:00'},
 {'Id': 853,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'MSR',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 2004,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS15-19',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '4.7 [3.6-6.0]',
  'NumericValue': 4.656455665,
  'Low': 3.553984537,
  'High': 6.007812628,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2004',
  'TimeDimensionBegin': '2004-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2004-12-31T00:00:00+01:00'},
 {'Id': 1006,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'CRI',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2008,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS15-19',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1.8 [1.7-2.0]',
  'NumericValue': 1.823161721,
  'Low': 1.66731276,
  'High': 1.98919441,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2008',
  'TimeDimensionBegin': '2008-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2008-12-31T00:00:00+01:00'},
 {'Id': 1008,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'UNSDGREGION',
  'SpatialDim': 'UNSDG_CENTRALASIA',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_MLE',
  'TimeDim': 1998,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS15-19',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '6.3 [6.2-6.5]',
  'NumericValue': 6.331402126,
  'Low': 6.161834196,
  'High': 6.491923906,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '1998',
  'TimeDimensionBegin': '1998-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1998-12-31T00:00:00+01:00'},
 {'Id': 1151,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SWZ',
  'ParentLocationCode': 'AFR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Africa',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_BTSX',
  'TimeDim': 1994,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-14',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '2.8 [0.0-8.7]',
  'NumericValue': 2.775697676,
  'Low': 0.0,
  'High': 8.698601205,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '1994',
  'TimeDimensionBegin': '1994-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1994-12-31T00:00:00+01:00'},
 {'Id': 1583,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'UNSDGREGION',
  'SpatialDim': 'UNSDG_CENTRALASIASOUTHERNASIA',
  'ParentLocationCode': None,
  'TimeDimType': 'YEAR',
  'ParentLocation': None,
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 2015,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-19',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '7.2 [6.7-7.8]',
  'NumericValue': 7.15115917,
  'Low': 6.652027452,
  'High': 7.79944913,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '2015',
  'TimeDimensionBegin': '2015-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '2015-12-31T00:00:00+01:00'},
 {'Id': 1621,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'SUR',
  'ParentLocationCode': 'AMR',
  'TimeDimType': 'YEAR',
  'ParentLocation': 'Americas',
  'Dim1Type': 'SEX',
  'Dim1': 'SEX_FMLE',
  'TimeDim': 1998,
  'Dim2Type': 'AGEGROUP',
  'Dim2': 'AGEGROUP_YEARS10-14',
  'Dim3Type': None,
  'Dim3': None,
  'DataSourceDimType': None,
  'DataSourceDim': None,
  'Value': '1.6 [1.3-1.9]',
  'NumericValue': 1.562747232,
  'Low': 1.279900786,
  'High': 1.866816425,
  'Comments': None,
  'Date': '2025-04-14T17:51:01.93+02:00',
  'TimeDimensionValue': '1998',
  'TimeDimensionBegin': '1998-01-01T00:00:00+01:00',
  'TimeDimensionEnd': '1998-12-31T00:00:00+01:00'},
 {'Id': 1823,
  'IndicatorCode': 'MORTADO',
  'SpatialDimType': 'COUNTRY',
  'SpatialDim': 'HUN',

In [46]:
sixthIndicatorDataDataFrame = pd.DataFrame(sixthIndicatorData)
sixthIndicatorDataDataFrame = sixthIndicatorDataDataFrame.loc[sixthIndicatorDataDataFrame['SpatialDim'].isin(countriesDf['Code'])]
sixthIndicatorDataDataFrame = sixthIndicatorDataDataFrame.loc[(sixthIndicatorDataDataFrame['Dim1'] == 'SEX_BTSX') & (sixthIndicatorDataDataFrame['Dim2'] == 'AGEGROUP_YEARS10-19')]
sixthIndicatorDataDataFrame['Value'] = sixthIndicatorDataDataFrame['Value'].astype('string')
sixthIndicatorDataDataFrame['Value'] = sixthIndicatorDataDataFrame['Value'].str.split(' ').str[0]
sixthIndicatorDataDataFrame['Value'] = sixthIndicatorDataDataFrame['Value'].astype('float')
sixthIndicatorDataDataFrame = sixthIndicatorDataDataFrame[['Id','IndicatorCode','SpatialDim','TimeDim','Dim1','Value']]
sixthIndicatorDataDataFrame

             Id IndicatorCode SpatialDim  TimeDim      Dim1  Value
110       13955       MORTADO        LTU     2016  SEX_BTSX    3.4
155       20067       MORTADO        CYP     1994  SEX_BTSX    4.2
212       27113       MORTADO        LTU     1995  SEX_BTSX    6.7
268       34177       MORTADO        EST     1991  SEX_BTSX    7.9
346       43925       MORTADO        LUX     2001  SEX_BTSX    2.1
...         ...           ...        ...      ...       ...    ...
75937  10173322       MORTADO        HRV     2021  SEX_BTSX    2.3
75959  10176508       MORTADO        DNK     2009  SEX_BTSX    1.8
76024  10184348       MORTADO        IRL     2004  SEX_BTSX    3.2
76092  10192613       MORTADO        BEL     2003  SEX_BTSX    2.8
76187  10205206       MORTADO        HRV     1998  SEX_BTSX    3.7

[918 rows x 6 columns]

In [ ]:
saveToParquet(sixthIndicatorDataDataFrame,'adolescentmortalityrate10-19')